#' Characterizes the fire regime and meteorology
#' @description Creates files with meteorological characterization of the study area during fire events (csv and fms files); and a word file with the characterization of the fire regime.
#' @param study.area Shapefile with the limits of the study area (polygon). Must not contain more than one polygon.
#' @param my.fires Polygon shapefile containing the fire perimeters (dated or not). This shapefile will be used to characterize the fire regime and to propose the durations to use in the MTT simulation. Must contain the fields “Year”, "ID" and "Area_ha".
#' @param my.dated.fires Polygon shapefile containing the dated fire perimeters. Same as the dated fire perimeters used in function get.fire.weather
#' @param meteo.data A csv file with the meteorological variables in the days with fire events. This file is generated by the function get.fire.weather, and stored as fire_weather_study_area.csv. The user might use a different file, as long as maintaining the same structure.
#' @param active.period The most common active period of fire spread. Will be used to select the interval of meteorological values to be used in the creation of clusters or percentiles.
#' @param user.period Optional. Numerical vector with the hours to be used in the fire weather characterization.
#' @param meteo.aggregation How hourly data should be combined into daily data. Possible methods include: mean (computes the mean of each variable for the active.period), max.min (computes the maximum value of temperature and wind speed and the minimum relative humidity for the active.period), none (does not combine hourly data into daily data and uses all the data in the creation of clusters or percentiles).
#' @param min.size Numerical. Minimum fire size to be considered in the analysis. Useful to subset the fire sample. Must be the same as the lowest value set in fire.size.intervals
#' @param min.overlap Numerical. Minimal overlap (as percentage) between the fire perimeters and the study area to consider the fire perimeter in the analysis. Must range between 0 and 100.
#' @param output.folder Path to the folder where the outputs should be saved.
#' @param fire.aggregation How the meteorology of different points inside the same fire perimeter should be combined. Possible methods include: WS (wind speed; the point falling inside the fire perimeter with highest wind speed is kept and the other ignored), none (uses all the points falling inside the fire perimeter).
#' @param fire.size.intervals Numeric vector with the fire size classes to be considered in the characterization of the study area.
#' @param manual.dur Optional. Numeric vector with the lower limits of each fire size class to be considered as a duration interval. To be used in the MTT calibration process (Run.fcontmtt function)
#' @param create.clusters Logical. True returns clusters generated by using kmeans and model-based clustering. False returns percentiles of the meteorological data.
#'
#' @return Returns fuel moisture file based on clustering or percentiles, a csv file with the meteorological values per clustering method, a csv file with a summary of meteorology per fire event, and a csv file with the fire size for the fires recorded in the study area in the period analysed.
#' @export
#' @import sf rgeos rgdal sp tibble tidyverse tseries ggpubr ggplot2 dplyr ggspatial rnaturalearth rnaturalearthdata RColorBrewer tidyquant factoextra car mclust officer flextable magrittr tidyr maps
#'
#' @examples
#' \dontrun{build_report(study.area="C:/user/study_area.shp",
#' my.fires="C:/user/my_fires.shp",my.dated.fires="C:/user/my_dated_fires.shp",
#' meteo.data="fire_weather_study_area.csv",active.period="energy",
#' user.period=c(14,15,16),meteo.aggregation="max.min",
#' min.size=100,min.overlap=50,fire.aggregation="WS",
#' fire.size.intervals=c(100,250,500,750,1000,2500,5000,10000),
#' create.clusters=TRUE,output.folder="C:/user/results")}
#'
build_report <- function(study.area, my.fires,my.dated.fires,meteo.data,active.period,user.period,meteo.aggregation,
                         min.size,min.overlap,output.folder,fire.aggregation,fire.size.intervals,
                         manual.dur,create.clusters) {
  my_study_area <- readOGR(study.area)
  my_fires <- readOGR(my.fires)
  result_hours_final <- read.csv(meteo.data,sep=",")

  my_study_area_t <- spTransform(my_study_area, CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"))

  my_study_area_t_plot <- my_study_area_t


  my_study_area_t <- st_as_sf(my_study_area_t)

  my_fires$Area_ha <- as.numeric(my_fires$Area_ha)


  my_fires <- gBuffer(my_fires,width=0,byid=TRUE)

  my_fires_t <- spTransform(my_fires, CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"))


  my_fires_t_inter <- st_as_sf(my_fires_t)



  world_st <- ne_countries(scale = "medium", returnclass = "sf")
  world_st <- st_make_valid(world_st)

  my_study_area_t_plot_st <- st_as_sf(my_study_area_t_plot)



  country_identified<-suppressMessages(base::as.data.frame(st_intersects(my_study_area_t_plot_st,world_st)))

  country_identified_final <- world_st[country_identified$col.id,"sovereignt"]

  country_identified_final_1 <- base::as.data.frame(country_identified_final)
  country_identified_final_1 <- country_identified_final_1[,"sovereignt"]
  country_identified_use <- unique(country_identified_final_1)

  WorldData <- map_data('world') %>% filter(region == country_identified_use) %>% fortify
  surroundings <- map_data('world') %>% fortify



  pt_study <- ggplot() +
    coord_fixed(xlim=c(min(WorldData$long),max(WorldData$long)),
                ylim = c(min(WorldData$lat),max(WorldData$lat)))+
    suppressWarnings(geom_map(data = surroundings, map = surroundings,
                              aes(x = long, y = lat, group = group, map_id=region),
                              fill = "grey", colour = "black", size=0.5))+
    suppressWarnings(geom_map(data = WorldData, map = WorldData,
                              aes(x = long, y = lat, group = group, map_id=region),
                              fill = "antiquewhite", colour = "black", size=0.5))+
    suppressMessages(geom_polygon(data = my_study_area_t_plot, aes(long, lat),
                                  colour = alpha("darkred", 1/2), size = 0.7, fill=NA,linetype = "dashed"))+
    theme(panel.grid.major = element_line(color = "gray", linetype = "dashed", size = 0.5),
          panel.background = element_rect(fill = "aliceblue"))+
    xlab("Longitude") + ylab("Latitude") + ggtitle("Study area location")

  pt_study_use <- tempfile(fileext = ".png")
  png(filename = pt_study_use, width = 4, height = 6, units = 'in', res = 300)
  plot(pt_study)
  dev.off()


  if (min.overlap==0){
    fire_inside_study_area <- suppressMessages(suppressWarnings(st_intersects(my_study_area_t,my_fires_t_inter)))

    fire_inside_study_area_df <- base::as.data.frame(fire_inside_study_area)

    my_fires_t_inter_intersected <- my_fires_t_inter[fire_inside_study_area_df$col.id,]


    my_fires_t_inter_intersected$Area_ha <- as.numeric(my_fires_t_inter_intersected$Area_ha)



  } else {
    my_study_area_t <- suppressMessages(suppressWarnings(st_buffer(my_study_area_t,0)))

    fire_inside_study_area_by_area <- suppressMessages(suppressWarnings(st_intersection(my_study_area_t,my_fires_t_inter)))
    fire_inside_study_area_by_area$area_correct <- as.numeric(round(st_area(fire_inside_study_area_by_area)/10000))

    fire_inside_study_area_by_area$Area_ha<-as.numeric(fire_inside_study_area_by_area$Area_ha)

    fire_inside_study_area_by_area$area_diff <- fire_inside_study_area_by_area$Area_ha-fire_inside_study_area_by_area$area_correct

    fire_inside_study_area_by_area$perc_inside <- fire_inside_study_area_by_area$area_correct * 100 / fire_inside_study_area_by_area$Area_ha


    my_fires_t_inter_intersected <- subset(fire_inside_study_area_by_area,perc_inside>=min.overlap)

    my_fires_t_inter_intersected$Area_ha <- as.numeric(my_fires_t_inter_intersected$Area_ha)



  }


  my_fires_t_inter_intersected_all_fires <- my_fires_t_inter_intersected

  my_fires_t_inter_intersected <- subset(my_fires_t_inter_intersected,Area_ha >=min.size)

  my_fires_t_inter_intersected_export <- base::as.data.frame(my_fires_t_inter_intersected)
  my_fires_t_inter_intersected_export <- my_fires_t_inter_intersected_export[,c("ID","Area_ha")]
  colnames(my_fires_t_inter_intersected_export) <- c("ID","Fire size")


  n_fires_considered <- length(as.numeric(unique(my_fires_t_inter_intersected$ID)))


  all_burned_area <- sum(my_fires_t_inter_intersected_all_fires$Area_ha)

  fires_below_100 <- subset(my_fires_t_inter_intersected_all_fires,Area_ha<100)
  fires_above_100_below_500 <- subset(my_fires_t_inter_intersected_all_fires,Area_ha>=100 & Area_ha <500)
  fires_above_500_below_1000 <- subset(my_fires_t_inter_intersected_all_fires,Area_ha>=500 & Area_ha <1000)
  fires_above_1000_below_5000 <- subset(my_fires_t_inter_intersected_all_fires,Area_ha>=1000 & Area_ha <5000)
  fires_above_5000 <- subset(my_fires_t_inter_intersected_all_fires,Area_ha>=5000)

  percentage_below_100 <- sum(fires_below_100$Area_ha)/all_burned_area*100
  percentage_above_100_below_500 <- sum(fires_above_100_below_500$Area_ha)/all_burned_area*100
  percentage_above_500_below_1000 <- sum(fires_above_500_below_1000$Area_ha)/all_burned_area*100
  percentage_above_1000_below_5000 <- sum(fires_above_1000_below_5000$Area_ha)/all_burned_area*100
  percentage_above_5000 <- sum(fires_above_5000$Area_ha)/all_burned_area*100

  table_for_graph <- base::as.data.frame(rbind(percentage_below_100,percentage_above_100_below_500,percentage_above_500_below_1000,
                                               percentage_above_1000_below_5000,percentage_above_5000))



  table_for_graph$V2 <- c("< 100","100 - 500",
                          "500 - 1000","1000 - 5000",
                          "> 5000")

  table_for_graph$order <- c(1:nrow(table_for_graph))

  table_for_graph$ymax = cumsum(table_for_graph$V1)

  table_for_graph$ymin = c(0, head(table_for_graph$ymax, n=-1))


  table_for_graph$labelPosition <- (table_for_graph$ymax + table_for_graph$ymin) / 2

  table_for_graph$label <- paste0(round (table_for_graph$V1,0), "%")


  cols <- c("< 100" = "#FFFFCC", "100 - 500" = "#FDD976",
            "500 - 1000" = "#FC8D3B", "1000 - 5000" = "#E21A1C",
            "> 5000" = "#800025")

  table_for_graph <- subset(table_for_graph,V1>0)



  plot_burned_area_per_class <- ggplot(table_for_graph, aes(ymax=ymax, ymin=ymin, xmax=4, xmin=3, fill=V2)) +
    geom_rect() +
    geom_label(x=3.5, aes(y=labelPosition, label=label), size=5, show.legend = FALSE,label.size = NA,fill = NA) +
    scale_fill_manual (values=cols,
                       breaks=c('< 100', '100 - 500', '500 - 1000', '1000 - 5000', '> 5000'))+
    coord_polar(theta="y") +
    xlim(c(2, 4)) +
    theme_void() +
    theme(legend.position = "bottom")+
    theme(legend.text=element_text(size=10),
          legend.title=element_text(size=12))+
    guides(fill=guide_legend(nrow=1,byrow=TRUE,title="Fire size (ha)"))



  plot_burned_area_per_class_use <- tempfile(fileext = ".png")
  png(filename = plot_burned_area_per_class_use, width = 6, height = 4, units = 'in', res = 300)
  plot(plot_burned_area_per_class)
  dev.off()



  myPal <- brewer.pal(8,"YlOrRd")





  freqs_my_fires_t_inter_intersected <- base::as.data.frame(my_fires_t_inter_intersected_all_fires %>%
                                                              mutate (class=cut(Area_ha,c(-1,99.9,250,500,750,1000,2500,5000,10000,10000000))) %>%
                                                              group_by(class) %>%
                                                              summarize(Total_areas = n())%>%
                                                              complete(class))

  freqs_my_fires_t_inter_intersected[is.na(freqs_my_fires_t_inter_intersected)] <- 0

  freqs_my_fires_t_inter_intersected$freq_rel <- freqs_my_fires_t_inter_intersected$Total_areas/sum(freqs_my_fires_t_inter_intersected$Total_areas)

  freqs_my_fires_t_inter_intersected$class <- c(1:9)

  size_dist <- ggplot(freqs_my_fires_t_inter_intersected, aes(x=class, y=freq_rel)) +
    geom_col(width = .7, position = "dodge", alpha=0.5)+
    scale_x_continuous(breaks= c(1, 2, 3,4,5,6,7,8,9),
                       labels= c("0-\n100","100-\n250","250-\n500","500-\n750","750-\n1000","1000-\n2500",
                                 "2500-\n5000","5000-\n10000",">10000"))+
    theme_tq()+
    scale_y_continuous(breaks = seq(0, (max(freqs_my_fires_t_inter_intersected$freq_rel)+0.05), by = 0.1))+
    theme(panel.grid.minor = element_blank(), axis.title=element_text(size=14),
          panel.grid.major.x = element_blank(), axis.text = element_text(size = 8),
          plot.title = element_text(size = 16), legend.position = "none",
          axis.ticks.length=unit(.15, "cm"),
          axis.ticks = element_line(colour = "black"))+
    ylab("Relative frequency") + xlab("Area (ha)")

  size_dist_use <- tempfile(fileext = ".png")
  png(filename = size_dist_use, width = 6, height = 4, units = 'in', res = 300)
  plot(size_dist)
  dev.off()



  BA_year_my_fires_t_inter_intersected <- base::as.data.frame(my_fires_t_inter_intersected_all_fires %>%
                                                                group_by(Year) %>%
                                                                summarize(Total_areas = sum(Area_ha)))





  my_BA_per_year <- matrix(ncol=2,nrow=length(min(BA_year_my_fires_t_inter_intersected$Year):max(BA_year_my_fires_t_inter_intersected$Year)))
  colnames(my_BA_per_year)<- c("Year","Burned_area")

  head(my_BA_per_year)
  my_BA_per_year <- base::as.data.frame(my_BA_per_year)

  my_BA_per_year$Year <- min(BA_year_my_fires_t_inter_intersected$Year):max(BA_year_my_fires_t_inter_intersected$Year)

  BA_year_my_fires_t_inter_intersected$Year <- as.numeric(BA_year_my_fires_t_inter_intersected$Year)


  my_BA_per_year <- left_join(my_BA_per_year,BA_year_my_fires_t_inter_intersected,by="Year")

  my_BA_per_year$Burned_area <- my_BA_per_year$Total_areas


  my_BA_per_year[is.na(my_BA_per_year)] <- 0


  my_BA_per_year_fin <- my_BA_per_year[,1:2]

  sum(my_BA_per_year_fin$Burned_area)

  my_BA_per_year_fin$cum_sum <- cumsum(my_BA_per_year_fin$Burned_area)
  my_BA_per_year_fin$cum_sum_perc <- my_BA_per_year_fin$cum_sum/sum(my_BA_per_year_fin$Burned_area)*100


  BA_dist <- ggplot(my_BA_per_year_fin, aes(x=Year, y=Burned_area)) +
    geom_col(width = .7, position = "dodge", alpha=0.5)+
    theme_tq()+
    theme(panel.grid.minor = element_blank(), axis.title=element_text(size=14),
          panel.grid.major.x = element_blank(), axis.text = element_text(size = 10),
          plot.title = element_text(size = 16), legend.position = "none",
          axis.ticks.length=unit(.15, "cm"),
          axis.ticks = element_line(colour = "black"))+

    ylab("Burned area (ha)") + xlab("Year") +
    scale_y_continuous(
      sec.axis = sec_axis(~ . / max(my_BA_per_year_fin$Burned_area)*100, name = "Cumulative burned area (%)")
    )+
    geom_line(aes(x=Year, y=cum_sum_perc*max(Burned_area)/100))

  BA_dist_use <- tempfile(fileext = ".png")
  png(filename = BA_dist_use, width = 6, height = 4, units = 'in', res = 300)
  plot(BA_dist)
  dev.off()











  #spike detection



  my_fires_t_inter_intersected$Area_ha <- as.numeric(my_fires_t_inter_intersected$Area_ha)

  freqs_my_fires_t_inter_intersected_spikes <- base::as.data.frame(my_fires_t_inter_intersected %>%
                                                                     mutate (class=cut(Area_ha,unique(c(min.size,fire.size.intervals,10000000)))) %>%
                                                                     group_by(class) %>%
                                                                     summarize(Total_areas = n())%>%
                                                                     complete(class))


  freqs_my_fires_t_inter_intersected_spikes <- subset(freqs_my_fires_t_inter_intersected_spikes, !is.na(class))

  freqs_my_fires_t_inter_intersected_spikes[is.na(freqs_my_fires_t_inter_intersected_spikes)] <- 0

  freqs_my_fires_t_inter_intersected_spikes$freq_rel <- freqs_my_fires_t_inter_intersected_spikes$Total_areas/sum(freqs_my_fires_t_inter_intersected_spikes$Total_areas)



  freqs_my_fires_t_inter_intersected_spikes$class <- c(1:nrow(freqs_my_fires_t_inter_intersected_spikes))

  fire.size.intervals

  automatic_lables_final <- numeric()

  for (i in 1:(length(fire.size.intervals)-1)){
    automatic_lables <- paste(fire.size.intervals[i],fire.size.intervals[i+1],sep="-\n")
    automatic_lables_final <- c(automatic_lables_final,automatic_lables)
  }

  size_dist_spike <- ggplot(freqs_my_fires_t_inter_intersected_spikes, aes(x=class, y=freq_rel)) +
    geom_col(width = .7, position = "dodge", alpha=0.5)+
    scale_x_continuous(breaks= c(1:nrow(freqs_my_fires_t_inter_intersected_spikes)),
                       labels= c(automatic_lables_final,paste(">",fire.size.intervals[length(fire.size.intervals)],sep="")))+
    theme_tq()+
    theme(panel.grid.minor = element_blank(), axis.title=element_text(size=14),
          panel.grid.major.x = element_blank(), axis.text = element_text(size = 7),
          plot.title = element_text(size = 16), legend.position = "none",
          axis.ticks.length=unit(.15, "cm"),

          axis.ticks = element_line(colour = "black"))+
    ylab("Relative frequency") + xlab("Area (ha)")


  size_dist_spike_use <- tempfile(fileext = ".png")
  png(filename = size_dist_spike_use, width = 6, height = 4, units = 'in', res = 300)
  plot(size_dist_spike)
  dev.off()







  y <- freqs_my_fires_t_inter_intersected_spikes$freq_rel
  y <- c(y,0)
  x <- 1:length(y)

  length(y)
  length(x)

  spike_detected <- peakdet(y,0.005,x)
  spike_detected_use <- spike_detected$maxtab


  freqs_my_fires_t_inter_intersected_spikes$lable_report <- c(automatic_lables_final,paste(">",fire.size.intervals[length(fire.size.intervals)],sep=""))



  freqs_my_fires_t_inter_intersected_spikes$lable_report



  freqs_my_fires_t_inter_intersected_spikes$first_val <- fire.size.intervals

  if (missing(manual.dur)){
    manual.dur <- c()
  }

  if (length(manual.dur)>=1 ){

    manual.dur_df <- base::as.data.frame(manual.dur)
    colnames(manual.dur_df) <- "pos"

    manual.dur_df_position <- freqs_my_fires_t_inter_intersected_spikes[freqs_my_fires_t_inter_intersected_spikes$first_val %in% manual.dur_df$pos, ]

    manual.dur_df$pos <- manual.dur_df_position$class


    for (w in 1:length(manual.dur)){

      if (w==length(manual.dur)) {
        final_w <- nrow(freqs_my_fires_t_inter_intersected_spikes)
      }else{
        final_w <- manual.dur_df$pos[w+1]-1
      }

      freqs_loop_man_dur <- freqs_my_fires_t_inter_intersected_spikes[manual.dur_df$pos[w]:final_w,]

      manual.dur_df[w,2]<-sum(freqs_loop_man_dur$freq_rel)
      colnames(manual.dur_df) <- c("pos","val")
    }

    spike_detected_use <- manual.dur_df
  }




  size_dist_spike <- ggplot(freqs_my_fires_t_inter_intersected_spikes, aes(x=class, y=freq_rel)) +
    geom_col(width = .7, position = "dodge", alpha=0.5)+
    scale_x_continuous(breaks= c(1:nrow(freqs_my_fires_t_inter_intersected_spikes)),
                       labels= c(automatic_lables_final,paste(">",fire.size.intervals[length(fire.size.intervals)],sep="")))+
    geom_vline(aes(xintercept=pos, colour="black"), spike_detected_use)+
    theme_tq()+
    theme(panel.grid.minor = element_blank(), axis.title=element_text(size=14),
          panel.grid.major.x = element_blank(), axis.text = element_text(size = 8),
          plot.title = element_text(size = 16), legend.position = "none",
          axis.ticks.length=unit(.15, "cm"),
          axis.ticks = element_line(colour = "black"))+
    ylab("Relative frequency") + xlab("Area (ha)")


  size_dist_spike_use <- tempfile(fileext = ".png")
  png(filename = size_dist_spike_use, width = 6, height = 4, units = 'in', res = 300)
  plot(size_dist_spike)
  dev.off()



  spike_detected_use$dur_ID <- 1:nrow(spike_detected_use)



  sum(freqs_my_fires_t_inter_intersected_spikes$freq_rel)
  freqs_my_fires_t_inter_intersected_spikes_id <- left_join(freqs_my_fires_t_inter_intersected_spikes,spike_detected_use,by=c("class"="pos"))
  freqs_my_fires_t_inter_intersected_spikes_id$cumsum_freq <- cumsum(freqs_my_fires_t_inter_intersected_spikes_id$freq_rel)


  if(is.na(freqs_my_fires_t_inter_intersected_spikes_id[1,"dur_ID"])){
    freqs_my_fires_t_inter_intersected_spikes_id[1,"dur_ID"]<-1
    freqs_my_fires_t_inter_intersected_spikes_id[1,"val"]<-freqs_my_fires_t_inter_intersected_spikes_id[1,"cumsum_freq"]
  }


  freqs_my_fires_t_inter_intersected_spikes_id$dur_ID <- na.locf(freqs_my_fires_t_inter_intersected_spikes_id$dur_ID)

  frequency_per_duration_class <- base::as.data.frame(freqs_my_fires_t_inter_intersected_spikes_id %>%
                                                        group_by(dur_ID) %>%
                                                        summarise(sum = sum(freq_rel)))



  #get meteo

  class(result_hours_final)

  result_hours_final_df<-base::as.data.frame(result_hours_final)

  #old - need to re-check
  # dated_fires <- st_read(my.dated.fires)
  # dated_fires <- st_make_valid(dated_fires)
  #
  # dated_fires <- st_transform(dated_fires, crs="EPSG:4326")
  #
  # dated_fires <- subset(dated_fires,Data_ini != "NaN" & Data_end != "NaN")


  dated_fires <- readOGR(my.dated.fires)
  dated_fires <- gBuffer(dated_fires,width=0,byid=TRUE)
  dated_fires <- spTransform(dated_fires, CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"))
  dated_fires <- st_as_sf(dated_fires)

  dated_fires <- subset(dated_fires,Data_ini != "NaN" & Data_end != "NaN")
  dated_fires <- st_make_valid(dated_fires)

  if (min.overlap==0){

    fire_inside_study_area_dated <- suppressMessages(suppressWarnings(st_intersects(my_study_area_t,dated_fires)))

    fire_inside_study_area_dated_df <- base::as.data.frame(fire_inside_study_area_dated)



    dated_fires_intersected <- dated_fires[fire_inside_study_area_dated_df$col.id,]


    dated_fires_intersected$Area_ha <- as.numeric(dated_fires_intersected$Area_ha)



  } else {

    my_study_area_t <- suppressMessages(suppressWarnings(st_buffer(my_study_area_t,0)))
    #dated_fires <- suppressMessages(suppressWarnings(st_buffer(dated_fires,0)))

    fire_inside_study_area_dated <- suppressMessages(suppressWarnings(st_intersects(my_study_area_t,dated_fires)))


    fire_inside_study_area_dated_df <- base::as.data.frame(fire_inside_study_area_dated)


    dated_fires_intersected <- dated_fires[fire_inside_study_area_dated_df$col.id,]


    fire_inside_study_area_by_area_dated <- suppressMessages(suppressWarnings(st_intersection(my_study_area_t,dated_fires_intersected)))
    fire_inside_study_area_by_area_dated$area_correct <- as.numeric(round(st_area(fire_inside_study_area_by_area_dated)/10000))


    fire_inside_study_area_by_area_dated$Area_ha<-as.numeric(fire_inside_study_area_by_area_dated$Area_ha)

    fire_inside_study_area_by_area_dated$area_diff <- fire_inside_study_area_by_area_dated$Area_ha-fire_inside_study_area_by_area_dated$area_correct

    fire_inside_study_area_by_area_dated$perc_inside <- fire_inside_study_area_by_area_dated$area_correct * 100 / fire_inside_study_area_by_area_dated$Area_ha


    dated_fires_intersected <- subset(fire_inside_study_area_by_area_dated,perc_inside>=min.overlap)

    dated_fires_intersected$Area_ha <- as.numeric(dated_fires_intersected$Area_ha)



  }


  dated_fires_intersected_all_fires <- dated_fires_intersected

  dated_fires_intersected <- subset(dated_fires_intersected,Area_ha >=min.size)



  dated_fires_join_use <- subset(dated_fires_intersected,perc_inside>1)
  dated_fires_intersected_all_fires <- subset(dated_fires_intersected_all_fires,perc_inside>1)



  meteo_fires_inside <- result_hours_final_df[result_hours_final_df$ID %in% dated_fires_join_use$ID, ]
  tail(meteo_fires_inside,100)

  nrow(meteo_fires_inside)


  if(active.period=="all") {
    meteo_fires_inside <- meteo_fires_inside
  }

  if(active.period=="energy") {
    meteo_fires_inside <- meteo_fires_inside[grep("12$|13$|14$|15$|16$|17$|18$|19$|20$", meteo_fires_inside$day_UTC_corrected ), ]
  }

  if(active.period=="user") {
    meteo_fires_inside <- meteo_fires_inside[grep(paste(user.period,collapse="$|","$",sep=""), meteo_fires_inside$day_UTC_corrected ), ]
  }




  head(meteo_fires_inside)


  meteo_fires_inside$day_use <- substr(meteo_fires_inside$day_UTC_corrected , 1, 8)
  meteo_fires_inside$concat_use <- paste0(meteo_fires_inside$ID,meteo_fires_inside$row,meteo_fires_inside$col,
                                          meteo_fires_inside$day_use)







  meteo_fires_inside_use_for_aggregation <- meteo_fires_inside[,c("ID", "row", "col", "lon",  "lat","concat_use")]

  meteo_fires_inside_wd_use <- meteo_fires_inside


  if(meteo.aggregation=="none") {
    meteo_fires_inside <- meteo_fires_inside
    names(meteo_fires_inside)[names(meteo_fires_inside) == 'temperature'] <- 'temperature_use'
    names(meteo_fires_inside)[names(meteo_fires_inside) == 'RH'] <- 'HR_use'
    names(meteo_fires_inside)[names(meteo_fires_inside) == 'WS'] <- 'WS_use'
    names(meteo_fires_inside)[names(meteo_fires_inside) == 'FWI'] <- 'FWI_use'
  }

  if(meteo.aggregation=="mean") {
    meteo_fires_inside1 <- base::as.data.frame(meteo_fires_inside %>%
                                                 group_by(concat_use) %>%
                                                 summarise(temperature_use = mean(temperature),
                                                           HR_use = mean(RH),
                                                           WS_use = mean(WS)))

    meteo_fires_inside1 <- left_join(meteo_fires_inside1,meteo_fires_inside_use_for_aggregation, by="concat_use",all.x=TRUE)
    meteo_fires_inside1 <- meteo_fires_inside1[!duplicated(meteo_fires_inside1),]

    meteo_fires_inside <- meteo_fires_inside1

  }


  if(meteo.aggregation=="max.min") {
    meteo_fires_inside1 <- base::as.data.frame(meteo_fires_inside %>%
                                                 group_by(concat_use) %>%
                                                 summarise(temperature_use = max(temperature),
                                                           HR_use = min(RH),
                                                           WS_use = max(WS)))

    meteo_fires_inside1 <- left_join(meteo_fires_inside1,meteo_fires_inside_use_for_aggregation, by="concat_use",all.x=TRUE)
    meteo_fires_inside1 <- meteo_fires_inside1[!duplicated(meteo_fires_inside1),]

    meteo_fires_inside <- meteo_fires_inside1

  }



  if (fire.aggregation=="WS"){
    meteo_fires_inside <- base::as.data.frame(meteo_fires_inside %>%
                                                group_by(ID) %>%
                                                slice(which.max(WS_use)))}


  if (fire.aggregation=="FWI"){
    meteo_fires_inside <- base::as.data.frame(meteo_fires_inside %>%
                                                group_by(ID) %>%
                                                slice(which.max(FWI_use)))}

  if (fire.aggregation=="none"){
    meteo_fires_inside <- meteo_fires_inside}


  meteo_fires_inside_wd_use <- meteo_fires_inside_wd_use[meteo_fires_inside_wd_use$concat_use %in% meteo_fires_inside$concat_use, ]




  meteo_fires_inside_wd_use$WD_use <- ifelse(meteo_fires_inside_wd_use$WD>=0 & meteo_fires_inside_wd_use$WD <=22.5, 0,
                                             ifelse(meteo_fires_inside_wd_use$WD>22.5 & meteo_fires_inside_wd_use$WD <=67.5, 45,
                                                    ifelse(meteo_fires_inside_wd_use$WD>67.5 & meteo_fires_inside_wd_use$WD <=112.5, 90,
                                                           ifelse(meteo_fires_inside_wd_use$WD>112.5 & meteo_fires_inside_wd_use$WD <=157.5, 135,
                                                                  ifelse(meteo_fires_inside_wd_use$WD>157.5 & meteo_fires_inside_wd_use$WD <=202.5, 180,
                                                                         ifelse(meteo_fires_inside_wd_use$WD>202.5 & meteo_fires_inside_wd_use$WD <=247.5, 225,
                                                                                ifelse(meteo_fires_inside_wd_use$WD>247.5 & meteo_fires_inside_wd_use$WD <=292.5, 270,
                                                                                       ifelse(meteo_fires_inside_wd_use$WD>292.5 & meteo_fires_inside_wd_use$WD <=337.5, 315,
                                                                                              ifelse(meteo_fires_inside_wd_use$WD>337.5, 0,NA)))))))))


  meteo_fires_inside_wd_use$WD_letter <- ifelse(meteo_fires_inside_wd_use$WD>=0 & meteo_fires_inside_wd_use$WD <=22.5, "N",
                                                ifelse(meteo_fires_inside_wd_use$WD>22.5 & meteo_fires_inside_wd_use$WD <=67.5, "NE",
                                                       ifelse(meteo_fires_inside_wd_use$WD>67.5 & meteo_fires_inside_wd_use$WD <=112.5, "E",
                                                              ifelse(meteo_fires_inside_wd_use$WD>112.5 & meteo_fires_inside_wd_use$WD <=157.5, "SE",
                                                                     ifelse(meteo_fires_inside_wd_use$WD>157.5 & meteo_fires_inside_wd_use$WD <=202.5, "S",
                                                                            ifelse(meteo_fires_inside_wd_use$WD>202.5 & meteo_fires_inside_wd_use$WD <=247.5, "SW",
                                                                                   ifelse(meteo_fires_inside_wd_use$WD>247.5 & meteo_fires_inside_wd_use$WD <=292.5, "W",
                                                                                          ifelse(meteo_fires_inside_wd_use$WD>292.5 & meteo_fires_inside_wd_use$WD <=337.5, "NW",
                                                                                                 ifelse(meteo_fires_inside_wd_use$WD>337.5, "N",NA)))))))))


  #substrRight <- function(x, n){
  #  substr(x, nchar(x)-n+1, nchar(x))
  #}


  meteo_fires_inside_summary_table <- meteo_fires_inside


  full_date <- substrRight(meteo_fires_inside_summary_table$concat_use, 8)

  day_x <- substrRight(full_date, 2)
  year_x <- substr(full_date, 1, 4)
  month_x_1 <- substrRight(full_date, 4)
  month_x <- substr(month_x_1,1, 2)


  meteo_fires_inside_summary_table$year <- year_x
  meteo_fires_inside_summary_table$month <- month_x
  meteo_fires_inside_summary_table$day <- day_x

  dated_fires_intersected$ID <- as.numeric(dated_fires_intersected$ID)

  meteo_fires_inside_summary_table <- base::as.data.frame(left_join(meteo_fires_inside_summary_table,dated_fires_intersected,by="ID"))


  table_to_summary <- meteo_fires_inside_summary_table[c("ID","year","month","day","temperature_use","HR_use","WS_use","Area_ha")]

  names(table_to_summary)[names(table_to_summary) == 'ID'] <- 'Fire ID'
  names(table_to_summary)[names(table_to_summary) == 'temperature_use'] <- 'T'
  names(table_to_summary)[names(table_to_summary) == 'HR_use'] <- 'RH'
  names(table_to_summary)[names(table_to_summary) == 'WS_use'] <- 'WS'
  names(table_to_summary)[names(table_to_summary) == 'Area_ha'] <- 'Fire size'


  #clustering

  if (create.clusters == TRUE){

    newdata <- meteo_fires_inside[c("temperature_use", "HR_use","WS_use")]
    df<-scale(newdata)

    mc <- Mclust(df)



    summary(mc, parameters=TRUE)
    mc$modelName
    optimal_mbc <- mc$G
    head(mc$z, 326)

    length(mc$classification)

    head(mc$classification,326)


    meteoclust_MB  <-base::data.frame(newdata, mc$classification)
    names(meteoclust_MB)
    clMB<-mc$classification


    BIC_fviz <- fviz_mclust(mc, "BIC", palette = "jco")

    BIC_modbas <- tempfile(fileext = ".png")
    png(filename = BIC_modbas, width = 5, height = 6, units = 'in', res = 300)
    plot(BIC_fviz)
    dev.off()


    if (length(unique(mc$classification))>1){
      class_fviz <- fviz_mclust(mc, "classification", geom = "point",
                                pointsize = 1.5, palette = "jco")


      uncer_fviz <- fviz_mclust(mc, "uncertainty", palette = "jco")




      class_modbas <- tempfile(fileext = ".png")
      png(filename = class_modbas, width = 5, height = 6, units = 'in', res = 300)
      plot(class_fviz)
      dev.off()


      uncer_modbas <- tempfile(fileext = ".png")
      png(filename = uncer_modbas, width = 5, height = 6, units = 'in', res = 300)
      plot(uncer_fviz)
      dev.off()
    }




    km.res2 <- eclust(df, FUNcluster="kmeans", k = 2, nstart = 50, graph = FALSE)
    km.res2$gap_stat
    km.res3 <- eclust(df, FUNcluster="kmeans", k =3, nstart = 50, graph = FALSE)
    km.res3$nbclust
    km.res4 <- eclust(df, FUNcluster="kmeans", k =4, nstart = 50, graph = FALSE)
    km.res5 <- eclust(df, FUNcluster="kmeans", k =5, nstart = 50, graph = FALSE)
    km.res6 <- eclust(df, FUNcluster="kmeans", k =6, nstart = 50, graph = FALSE)
    km.res7 <- eclust(df, FUNcluster="kmeans", k =7, nstart = 50, graph = FALSE)
    km.res8 <- eclust(df, FUNcluster="kmeans", k =8, nstart = 50, graph = FALSE)
    km.res9 <- eclust(df, FUNcluster="kmeans", k =9, nstart = 50, graph = FALSE)
    km.res10 <- eclust(df, FUNcluster="kmeans", k =10, nstart = 50, graph = FALSE)




    sil_kmean2 <- fviz_silhouette(km.res2, label = FALSE, print.summary = FALSE)+ theme(title = element_text(size = 8))
    sil_kmean3 <- fviz_silhouette(km.res3, label = FALSE, print.summary = FALSE)+ theme(title = element_text(size = 8))
    sil_kmean4 <- fviz_silhouette(km.res4, label = FALSE, print.summary = FALSE)+ theme(title = element_text(size = 8))
    sil_kmean5 <- fviz_silhouette(km.res5, label = FALSE, print.summary = FALSE)+ theme(title = element_text(size = 8))
    sil_kmean6 <- fviz_silhouette(km.res6, label = FALSE, print.summary = FALSE)+ theme(title = element_text(size = 8))
    sil_kmean7 <- fviz_silhouette(km.res7, label = FALSE, print.summary = FALSE)+ theme(title = element_text(size = 8))
    sil_kmean8 <- fviz_silhouette(km.res8, label = FALSE, print.summary = FALSE)+ theme(title = element_text(size = 8))
    sil_kmean9 <- fviz_silhouette(km.res9, label = FALSE, print.summary = FALSE)+ theme(title = element_text(size = 8))
    sil_kmean10 <- fviz_silhouette(km.res10, label = FALSE, print.summary = FALSE)+ theme(title = element_text(size = 8))


    kmeans_all <- ggarrange(sil_kmean2, sil_kmean3, sil_kmean4,sil_kmean5,
                            sil_kmean6,sil_kmean7,sil_kmean8,sil_kmean9,sil_kmean10,
                            labels = c("A", "B", "C","D","E", "F", "G","H","G"),
                            ncol = 2, nrow = 5, legend="none")


    kmeans_all_use <- tempfile(fileext = ".png")
    png(filename = kmeans_all_use, width = 5, height = 6, units = 'in', res = 300)
    plot(kmeans_all)
    dev.off()






    clKM3<-km.res3$cluster

    meteoclust_KM3  <-base::data.frame(newdata, clKM3)
    names(meteoclust_KM3)


    meteo1<-suppressWarnings(aggregate(meteo_fires_inside, by=list(cluster=mc$classification), mean)) ### model-based clusters
    meteo2<-suppressWarnings(aggregate(meteo_fires_inside, by=list(cluster=km.res2$cluster), mean))  ### kmeans 2 clusters
    meteo3<-suppressWarnings(aggregate(meteo_fires_inside, by=list(cluster=km.res3$cluster), mean)) ### kmeans 3 clusters
    meteo4<-suppressWarnings(aggregate(meteo_fires_inside, by=list(cluster=km.res4$cluster), mean)) ### kmeans 4 clusters
    meteo5<-suppressWarnings(aggregate(meteo_fires_inside, by=list(cluster=km.res5$cluster), mean)) ### kmeans 5 clusters
    meteo6<-suppressWarnings(aggregate(meteo_fires_inside, by=list(cluster=km.res6$cluster), mean)) ### kmeans 6 clusters
    meteo7<-suppressWarnings(aggregate(meteo_fires_inside, by=list(cluster=km.res7$cluster), mean)) ### kmeans 7 clusters
    meteo8<-suppressWarnings(aggregate(meteo_fires_inside, by=list(cluster=km.res8$cluster), mean)) ### kmeans 8 clusters
    meteo9<-suppressWarnings(aggregate(meteo_fires_inside, by=list(cluster=km.res9$cluster), mean)) ### kmeans 9 clusters
    meteo10<-suppressWarnings(aggregate(meteo_fires_inside, by=list(cluster=km.res10$cluster), mean)) ### kmeans 10 clusters



    mc_df <- base::as.data.frame(mc$classification)


    mc_df_fin <- mc_df %>%
      group_by(mc$classification) %>%
      summarise(count=n())

    meteo1$size <- mc_df_fin$count
    meteo2$size <- km.res2$size
    meteo3$size <- km.res3$size
    meteo4$size <- km.res4$size
    meteo5$size <- km.res5$size
    meteo6$size <- km.res6$size
    meteo7$size <- km.res7$size
    meteo8$size <- km.res8$size
    meteo9$size <- km.res9$size
    meteo10$size <- km.res10$size





    meteoclust_MB <- mc$classification


    # Silhouette method
    silhouette <- fviz_nbclust(df, kmeans, method = "silhouette")+
      labs(subtitle = "Silhouette method")

    #Total within sum of square method
    elbow <- fviz_nbclust(df, kmeans, method = "wss")+
      labs(subtitle = "Total within sum of square method (Elbow method)")

    elbow$data




    silhouette_use <- tempfile(fileext = ".png")
    png(filename = silhouette_use, width = 6, height = 4, units = 'in', res = 300)
    plot(silhouette)
    dev.off()


    elbow_use <- tempfile(fileext = ".png")
    png(filename = elbow_use, width = 6, height = 4, units = 'in', res = 300)
    plot(elbow)
    dev.off()




    meteo_fires_inside$cluster_id_MB <- meteoclust_MB
    meteo_fires_inside$cluster_id_km_2 <- km.res2$cluster
    meteo_fires_inside$cluster_id_km_3 <- km.res3$cluster
    meteo_fires_inside$cluster_id_km_4 <- km.res4$cluster
    meteo_fires_inside$cluster_id_km_5 <- km.res5$cluster
    meteo_fires_inside$cluster_id_km_6 <- km.res6$cluster
    meteo_fires_inside$cluster_id_km_7 <- km.res7$cluster
    meteo_fires_inside$cluster_id_km_8 <- km.res8$cluster
    meteo_fires_inside$cluster_id_km_9 <- km.res9$cluster
    meteo_fires_inside$cluster_id_km_10 <- km.res10$cluster


    meteo_fires_inside_wd_use$concat_use_2 <- paste(meteo_fires_inside_wd_use$ID,
                                                    meteo_fires_inside_wd_use$day_UTC_corrected,
                                                    sep="_")



    meteo_fires_inside_wd_use <- meteo_fires_inside_wd_use[!duplicated(meteo_fires_inside_wd_use), ]


    if (meteo.aggregation=="none"){
      meteo_fires_inside_wd_use$cluster_id_MB <- meteoclust_MB
      meteo_fires_inside_wd_use$cluster_id_km_2 <- km.res2$cluster
      meteo_fires_inside_wd_use$cluster_id_km_3 <- km.res3$cluster
      meteo_fires_inside_wd_use$cluster_id_km_4 <- km.res4$cluster
      meteo_fires_inside_wd_use$cluster_id_km_5 <- km.res5$cluster
      meteo_fires_inside_wd_use$cluster_id_km_6 <- km.res6$cluster
      meteo_fires_inside_wd_use$cluster_id_km_7 <- km.res7$cluster
      meteo_fires_inside_wd_use$cluster_id_km_8 <- km.res8$cluster
      meteo_fires_inside_wd_use$cluster_id_km_9 <- km.res9$cluster
      meteo_fires_inside_wd_use$cluster_id_km_10 <- km.res10$cluster

    } else {



      n_unique <- length(unique(meteo_fires_inside_wd_use$concat_use))
      n_reps <- nrow(meteo_fires_inside_wd_use)/n_unique

      meteo_fires_inside_wd_use$cluster_id_MB <- rep(meteoclust_MB, each = n_reps)
      meteo_fires_inside_wd_use$cluster_id_km_2 <- rep(km.res2$cluster,each=n_reps)
      meteo_fires_inside_wd_use$cluster_id_km_3 <- rep(km.res3$cluster,each=n_reps)
      meteo_fires_inside_wd_use$cluster_id_km_4 <- rep(km.res4$cluster,each=n_reps)
      meteo_fires_inside_wd_use$cluster_id_km_5 <- rep(km.res5$cluster,each=n_reps)
      meteo_fires_inside_wd_use$cluster_id_km_6 <- rep(km.res6$cluster,each=n_reps)
      meteo_fires_inside_wd_use$cluster_id_km_7 <- rep(km.res7$cluster,each=n_reps)
      meteo_fires_inside_wd_use$cluster_id_km_8 <- rep(km.res8$cluster,each=n_reps)
      meteo_fires_inside_wd_use$cluster_id_km_9 <- rep(km.res9$cluster,each=n_reps)
      meteo_fires_inside_wd_use$cluster_id_km_10 <- rep(km.res10$cluster,each=n_reps)}



    freqs_wd_MB <- base::as.data.frame(meteo_fires_inside_wd_use%>%
                                         group_by(cluster_id_MB,WD_use,WD_letter)%>%
                                         summarise(Freq=n()/nrow(meteo_fires_inside_wd_use)))


    freqs_wd_km_2 <- base::as.data.frame(meteo_fires_inside_wd_use%>%
                                           group_by(cluster_id_km_2,WD_use,WD_letter)%>%
                                           summarise(Freq=n()/nrow(meteo_fires_inside_wd_use)))

    freqs_wd_km_3 <- base::as.data.frame(meteo_fires_inside_wd_use%>%
                                           group_by(cluster_id_km_3,WD_use,WD_letter)%>%
                                           summarise(Freq=n()/nrow(meteo_fires_inside_wd_use)))

    freqs_wd_km_4 <- base::as.data.frame(meteo_fires_inside_wd_use%>%
                                           group_by(cluster_id_km_4,WD_use,WD_letter)%>%
                                           summarise(Freq=n()/nrow(meteo_fires_inside_wd_use)))

    freqs_wd_km_5 <- base::as.data.frame(meteo_fires_inside_wd_use%>%
                                           group_by(cluster_id_km_5,WD_use,WD_letter)%>%
                                           summarise(Freq=n()/nrow(meteo_fires_inside_wd_use)))


    freqs_wd_km_6 <- base::as.data.frame(meteo_fires_inside_wd_use%>%
                                           group_by(cluster_id_km_6,WD_use,WD_letter)%>%
                                           summarise(Freq=n()/nrow(meteo_fires_inside_wd_use)))

    freqs_wd_km_7 <- base::as.data.frame(meteo_fires_inside_wd_use%>%
                                           group_by(cluster_id_km_7,WD_use,WD_letter)%>%
                                           summarise(Freq=n()/nrow(meteo_fires_inside_wd_use)))

    freqs_wd_km_8 <- base::as.data.frame(meteo_fires_inside_wd_use%>%
                                           group_by(cluster_id_km_8,WD_use,WD_letter)%>%
                                           summarise(Freq=n()/nrow(meteo_fires_inside_wd_use)))

    freqs_wd_km_9 <- base::as.data.frame(meteo_fires_inside_wd_use%>%
                                           group_by(cluster_id_km_9,WD_use,WD_letter)%>%
                                           summarise(Freq=n()/nrow(meteo_fires_inside_wd_use)))

    freqs_wd_km_10 <- base::as.data.frame(meteo_fires_inside_wd_use%>%
                                            group_by(cluster_id_km_10,WD_use,WD_letter)%>%
                                            summarise(Freq=n()/nrow(meteo_fires_inside_wd_use)))




    freqs_wd_MB
    frequency_per_duration_class



    for(i in 1:nrow(frequency_per_duration_class)){
      nome <- paste("duration_",i,sep="")
      freqs_wd_MB[[nome]] <- freqs_wd_MB$Freq*frequency_per_duration_class$sum[i]
    }


    for(i in 1:nrow(frequency_per_duration_class)){
      nome <- paste("duration_",i,sep="")
      freqs_wd_km_2[[nome]] <- freqs_wd_km_2$Freq*frequency_per_duration_class$sum[i]
    }


    for(i in 1:nrow(frequency_per_duration_class)){
      nome <- paste("duration_",i,sep="")
      freqs_wd_km_3[[nome]] <- freqs_wd_km_3$Freq*frequency_per_duration_class$sum[i]
    }


    for(i in 1:nrow(frequency_per_duration_class)){
      nome <- paste("duration_",i,sep="")
      freqs_wd_km_4[[nome]] <- freqs_wd_km_4$Freq*frequency_per_duration_class$sum[i]
    }


    for(i in 1:nrow(frequency_per_duration_class)){
      nome <- paste("duration_",i,sep="")
      freqs_wd_km_5[[nome]] <- freqs_wd_km_5$Freq*frequency_per_duration_class$sum[i]
    }


    for(i in 1:nrow(frequency_per_duration_class)){
      nome <- paste("duration_",i,sep="")
      freqs_wd_km_6[[nome]] <- freqs_wd_km_6$Freq*frequency_per_duration_class$sum[i]
    }


    for(i in 1:nrow(frequency_per_duration_class)){
      nome <- paste("duration_",i,sep="")
      freqs_wd_km_7[[nome]] <- freqs_wd_km_7$Freq*frequency_per_duration_class$sum[i]
    }


    for(i in 1:nrow(frequency_per_duration_class)){
      nome <- paste("duration_",i,sep="")
      freqs_wd_km_8[[nome]] <- freqs_wd_km_8$Freq*frequency_per_duration_class$sum[i]
    }


    for(i in 1:nrow(frequency_per_duration_class)){
      nome <- paste("duration_",i,sep="")
      freqs_wd_km_9[[nome]] <- freqs_wd_km_9$Freq*frequency_per_duration_class$sum[i]
    }


    for(i in 1:nrow(frequency_per_duration_class)){
      nome <- paste("duration_",i,sep="")
      freqs_wd_km_10[[nome]] <- freqs_wd_km_10$Freq*frequency_per_duration_class$sum[i]
    }

    length(unique(meteo_fires_inside_wd_use$ID))
    length(unique(dated_fires_intersected$ID))

    my_fires_t_inter_intersected$ID<-as.numeric(my_fires_t_inter_intersected$ID)

    my_fires_t_inter_intersected_clusters_get_area <- base::as.data.frame(left_join(dated_fires_intersected,meteo_fires_inside_wd_use,by="ID"))
    head(my_fires_t_inter_intersected_clusters_get_area)

    my_fires_t_inter_intersected_clusters_get_area <- subset(my_fires_t_inter_intersected_clusters_get_area, !is.na(cluster_id_MB))


    if (meteo.aggregation!="none"){
      my_fires_t_inter_intersected_clusters_get_area<-my_fires_t_inter_intersected_clusters_get_area[!duplicated(my_fires_t_inter_intersected_clusters_get_area$ID), ]

    }

    area_per_cluster_id_MB <- base::as.data.frame(my_fires_t_inter_intersected_clusters_get_area %>%
                                                    group_by(cluster_id_MB) %>%
                                                    summarise(mean_area_ha=mean(Area_ha),
                                                              per_95_area_ha=quantile(Area_ha,probs= c(0.95),na.rm=T),
                                                              per_5_area_ha=quantile(Area_ha,probs= c(0.05),na.rm=T)))


    area_per_cluster_id_km_2 <- base::as.data.frame(my_fires_t_inter_intersected_clusters_get_area %>%
                                                      group_by(cluster_id_km_2) %>%
                                                      summarise(mean_area_ha=mean(Area_ha),
                                                                per_95_area_ha=quantile(Area_ha,probs= c(0.95),na.rm=T),
                                                                per_5_area_ha=quantile(Area_ha,probs= c(0.05),na.rm=T)))


    area_per_cluster_id_km_3 <- base::as.data.frame(my_fires_t_inter_intersected_clusters_get_area %>%
                                                      group_by(cluster_id_km_3) %>%
                                                      summarise(mean_area_ha=mean(Area_ha),
                                                                per_95_area_ha=quantile(Area_ha,probs= c(0.95),na.rm=T),
                                                                per_5_area_ha=quantile(Area_ha,probs= c(0.05),na.rm=T)))


    area_per_cluster_id_km_4 <- base::as.data.frame(my_fires_t_inter_intersected_clusters_get_area %>%
                                                      group_by(cluster_id_km_4) %>%
                                                      summarise(mean_area_ha=mean(Area_ha),
                                                                per_95_area_ha=quantile(Area_ha,probs= c(0.95),na.rm=T),
                                                                per_5_area_ha=quantile(Area_ha,probs= c(0.05),na.rm=T)))



    area_per_cluster_id_km_5 <- base::as.data.frame(my_fires_t_inter_intersected_clusters_get_area %>%
                                                      group_by(cluster_id_km_5) %>%
                                                      summarise(mean_area_ha=mean(Area_ha),
                                                                per_95_area_ha=quantile(Area_ha,probs= c(0.95),na.rm=T),
                                                                per_5_area_ha=quantile(Area_ha,probs= c(0.05),na.rm=T)))


    area_per_cluster_id_km_6 <- base::as.data.frame(my_fires_t_inter_intersected_clusters_get_area %>%
                                                      group_by(cluster_id_km_6) %>%
                                                      summarise(mean_area_ha=mean(Area_ha),
                                                                per_95_area_ha=quantile(Area_ha,probs= c(0.95),na.rm=T),
                                                                per_5_area_ha=quantile(Area_ha,probs= c(0.05),na.rm=T)))


    area_per_cluster_id_km_7 <- base::as.data.frame(my_fires_t_inter_intersected_clusters_get_area %>%
                                                      group_by(cluster_id_km_7) %>%
                                                      summarise(mean_area_ha=mean(Area_ha),
                                                                per_95_area_ha=quantile(Area_ha,probs= c(0.95),na.rm=T),
                                                                per_5_area_ha=quantile(Area_ha,probs= c(0.05),na.rm=T)))


    area_per_cluster_id_km_8 <- base::as.data.frame(my_fires_t_inter_intersected_clusters_get_area %>%
                                                      group_by(cluster_id_km_8) %>%
                                                      summarise(mean_area_ha=mean(Area_ha),
                                                                per_95_area_ha=quantile(Area_ha,probs= c(0.95),na.rm=T),
                                                                per_5_area_ha=quantile(Area_ha,probs= c(0.05),na.rm=T)))


    area_per_cluster_id_km_9 <- base::as.data.frame(my_fires_t_inter_intersected_clusters_get_area %>%
                                                      group_by(cluster_id_km_9) %>%
                                                      summarise(mean_area_ha=mean(Area_ha),
                                                                per_95_area_ha=quantile(Area_ha,probs= c(0.95),na.rm=T),
                                                                per_5_area_ha=quantile(Area_ha,probs= c(0.05),na.rm=T)))


    area_per_cluster_id_km_10 <- base::as.data.frame(my_fires_t_inter_intersected_clusters_get_area %>%
                                                       group_by(cluster_id_km_10) %>%
                                                       summarise(mean_area_ha=mean(Area_ha),
                                                                 per_95_area_ha=quantile(Area_ha,probs= c(0.95),na.rm=T),
                                                                 per_5_area_ha=quantile(Area_ha,probs= c(0.05),na.rm=T)))




    meteo1$mean_area_ha <- area_per_cluster_id_MB$mean_area_ha
    meteo1$per95_area_ha <- area_per_cluster_id_MB$per_95_area_ha
    meteo1$per05_area_ha <- area_per_cluster_id_MB$per_5_area_ha


    meteo2$mean_area_ha <- area_per_cluster_id_km_2$mean_area_ha
    meteo2$per95_area_ha <- area_per_cluster_id_km_2$per_95_area_ha
    meteo2$per05_area_ha <- area_per_cluster_id_km_2$per_5_area_ha

    meteo3$mean_area_ha <- area_per_cluster_id_km_3$mean_area_ha
    meteo3$per95_area_ha <- area_per_cluster_id_km_3$per_95_area_ha
    meteo3$per05_area_ha <- area_per_cluster_id_km_3$per_5_area_ha

    meteo4$mean_area_ha <- area_per_cluster_id_km_4$mean_area_ha
    meteo4$per95_area_ha <- area_per_cluster_id_km_4$per_95_area_ha
    meteo4$per05_area_ha <- area_per_cluster_id_km_4$per_5_area_ha

    meteo5$mean_area_ha <- area_per_cluster_id_km_5$mean_area_ha
    meteo5$per95_area_ha <- area_per_cluster_id_km_5$per_95_area_ha
    meteo5$per05_area_ha <- area_per_cluster_id_km_5$per_5_area_ha

    meteo6$mean_area_ha <- area_per_cluster_id_km_6$mean_area_ha
    meteo6$per95_area_ha <- area_per_cluster_id_km_6$per_95_area_ha
    meteo6$per05_area_ha <- area_per_cluster_id_km_6$per_5_area_ha

    meteo7$mean_area_ha <- area_per_cluster_id_km_7$mean_area_ha
    meteo7$per95_area_ha <- area_per_cluster_id_km_7$per_95_area_ha
    meteo7$per05_area_ha <- area_per_cluster_id_km_7$per_5_area_ha

    meteo8$mean_area_ha <- area_per_cluster_id_km_8$mean_area_ha
    meteo8$per95_area_ha <- area_per_cluster_id_km_8$per_95_area_ha
    meteo8$per05_area_ha <- area_per_cluster_id_km_8$per_5_area_ha

    meteo9$mean_area_ha <- area_per_cluster_id_km_9$mean_area_ha
    meteo9$per95_area_ha <- area_per_cluster_id_km_9$per_95_area_ha
    meteo9$per05_area_ha <- area_per_cluster_id_km_9$per_5_area_ha

    meteo10$mean_area_ha <- area_per_cluster_id_km_10$mean_area_ha
    meteo10$per95_area_ha <- area_per_cluster_id_km_10$per_95_area_ha
    meteo10$per05_area_ha <- area_per_cluster_id_km_10$per_5_area_ha






    freqs_wd_MB_use <- freqs_wd_MB[,c("cluster_id_MB","WD_letter","Freq")]

    freqs_wd_km_2_use <- freqs_wd_km_2[,c("cluster_id_km_2","WD_letter","Freq")]
    freqs_wd_km_3_use <- freqs_wd_km_3[,c("cluster_id_km_3","WD_letter","Freq")]
    freqs_wd_km_4_use <- freqs_wd_km_4[,c("cluster_id_km_4","WD_letter","Freq")]
    freqs_wd_km_5_use <- freqs_wd_km_5[,c("cluster_id_km_5","WD_letter","Freq")]
    freqs_wd_km_6_use <- freqs_wd_km_6[,c("cluster_id_km_6","WD_letter","Freq")]
    freqs_wd_km_7_use <- freqs_wd_km_7[,c("cluster_id_km_7","WD_letter","Freq")]
    freqs_wd_km_8_use <- freqs_wd_km_8[,c("cluster_id_km_8","WD_letter","Freq")]
    freqs_wd_km_9_use <- freqs_wd_km_9[,c("cluster_id_km_9","WD_letter","Freq")]
    freqs_wd_km_10_use <- freqs_wd_km_10[,c("cluster_id_km_10","WD_letter","Freq")]


  } else {

    newdata <- meteo_fires_inside[c("temperature_use", "HR_use","WS_use")]

    temp_90 <- as.numeric(quantile(newdata$temperature_use,0.9))
    temp_80 <- as.numeric(quantile(newdata$temperature_use,0.8))
    temp_70 <- as.numeric(quantile(newdata$temperature_use,0.7))
    temp_60 <- as.numeric(quantile(newdata$temperature_use,0.6))
    temp_50 <- as.numeric(quantile(newdata$temperature_use,0.5))

    WS_90 <- as.numeric(quantile(newdata$WS_use,0.9))
    WS_80 <- as.numeric(quantile(newdata$WS_use,0.8))
    WS_70 <- as.numeric(quantile(newdata$WS_use,0.7))
    WS_60 <- as.numeric(quantile(newdata$WS_use,0.6))
    WS_50 <- as.numeric(quantile(newdata$WS_use,0.5))


    HR_10 <- as.numeric(quantile(newdata$HR_use,0.1))
    HR_20 <- as.numeric(quantile(newdata$HR_use,0.2))
    HR_30 <- as.numeric(quantile(newdata$HR_use,0.3))
    HR_40 <- as.numeric(quantile(newdata$HR_use,0.4))
    HR_50 <- as.numeric(quantile(newdata$HR_use,0.5))


    percentile_90 <- base::as.data.frame(cbind(temp_90,HR_10,WS_90))
    percentile_80 <- base::as.data.frame(cbind(temp_80,HR_20,WS_80))
    percentile_70 <- base::as.data.frame(cbind(temp_70,HR_30,WS_70))
    percentile_60 <- base::as.data.frame(cbind(temp_60,HR_40,WS_60))
    percentile_50 <- base::as.data.frame(cbind(temp_50,HR_50,WS_50))


    colnames(percentile_90) <- c("temperature_use", "HR_use","WS_use")
    colnames(percentile_80) <- c("temperature_use", "HR_use","WS_use")
    colnames(percentile_70) <- c("temperature_use", "HR_use","WS_use")
    colnames(percentile_60) <- c("temperature_use", "HR_use","WS_use")
    colnames(percentile_50) <- c("temperature_use", "HR_use","WS_use")


    all_percentiles <- rbind(percentile_50,percentile_60,percentile_70,percentile_80,percentile_90)
    all_percentiles$percentile <- c(50,60,70,80,90)

    all_percentiles <- cbind(base::as.data.frame(all_percentiles[,4]),all_percentiles[,1:3])
    colnames(all_percentiles) <- c("percentile","temperature_use", "HR_use","WS_use")


    percentile_wd <- base::as.data.frame(meteo_fires_inside_wd_use %>%
                                           group_by(WD_use,WD_letter) %>%
                                           summarise(absolute_freq = n()))

    percentile_wd$Freq <- percentile_wd$absolute_freq/sum(percentile_wd$absolute_freq)
    percentile_wd_use <- percentile_wd[,c(2,4)]


    all_percentiles_wd <- all_percentiles[rep(seq_len(nrow(all_percentiles)), each = nrow(percentile_wd_use)), ]
    all_percentiles_wd <- cbind(all_percentiles_wd,percentile_wd_use)


  }



  result_hours_final[is.na(result_hours_final$WD),]





  if(active.period=="all") {
    result_hours_final_df_wind_rose <- result_hours_final_df
  }

  if(active.period=="energy") {
    result_hours_final_df_wind_rose <- result_hours_final_df[grep("12$|13$|14$|15$|16$|17$|18$|19$|20$", result_hours_final_df$day_UTC_corrected ), ]
  }

  if(active.period=="user") {
    result_hours_final_df_wind_rose <- result_hours_final_df[grep(paste(user.period,collapse="$|","$",sep=""), result_hours_final_df$day_UTC_corrected ), ]
  }





  for_wind_rose_0ha <- subset(dated_fires_intersected_all_fires,area_correct>=0)
  for_wind_rose_0ha$Area_ha <- as.numeric(for_wind_rose_0ha$Area_ha)
  for_wind_rose_0ha_meteo_fires_inside <- result_hours_final_df_wind_rose[result_hours_final_df_wind_rose$ID %in% for_wind_rose_0ha$ID, ]




  p0 <- plot_windrose(spd = for_wind_rose_0ha_meteo_fires_inside$WS,
                      dir = for_wind_rose_0ha_meteo_fires_inside$WD,
                      spdseq = c(0,3,6,12,20,ceiling(max(for_wind_rose_0ha_meteo_fires_inside$WS))))



  wind_rose_use <- tempfile(fileext = ".png")
  png(filename = wind_rose_use, width = 4, height = 4, units = 'in', res = 300)
  plot(p0)
  dev.off()




  for_wind_rose_100ha <- subset(dated_fires_intersected_all_fires,area_correct>=100)
  for_wind_rose_100ha$Area_ha <- as.numeric(for_wind_rose_100ha$Area_ha)
  for_wind_rose_100ha_meteo_fires_inside <- result_hours_final_df_wind_rose[result_hours_final_df_wind_rose$ID %in% for_wind_rose_100ha$ID, ]




  if (nrow(for_wind_rose_100ha_meteo_fires_inside)>0){
    p100 <- plot_windrose(spd = for_wind_rose_100ha_meteo_fires_inside$WS,
                          dir = for_wind_rose_100ha_meteo_fires_inside$WD,
                          spdseq = c(0,3,6,12,20,ceiling(max(for_wind_rose_0ha_meteo_fires_inside$WS))))
  }else{p100 <- ggplot() +
    annotate("text", x = 0.5,  y = 0.5,
             size = 3,
             label = "No fire events with more than \n 100 ha burned recorded") + theme_void()
  }


  wind_rose_100_use <- tempfile(fileext = ".png")
  png(filename = wind_rose_100_use, width = 4, height = 4, units = 'in', res = 300)
  plot(p100)
  dev.off()



  for_wind_rose_500ha <- subset(dated_fires_intersected_all_fires,area_correct>=500)
  for_wind_rose_500ha$Area_ha <- as.numeric(for_wind_rose_500ha$Area_ha)
  for_wind_rose_500ha_meteo_fires_inside <- result_hours_final_df_wind_rose[result_hours_final_df_wind_rose$ID %in% for_wind_rose_500ha$ID, ]

  if (nrow(for_wind_rose_500ha_meteo_fires_inside)>0){
    p500 <- plot_windrose(spd = for_wind_rose_500ha_meteo_fires_inside$WS,
                          dir = for_wind_rose_500ha_meteo_fires_inside$WD,
                          spdseq = c(0,3,6,12,20,ceiling(max(for_wind_rose_0ha_meteo_fires_inside$WS))))
  } else{p500 <- ggplot() +
    annotate("text", x = 0.5,  y = 0.5,
             size = 3,
             label = "No fire events with more than \n 500 ha burned recorded") + theme_void()
  }



  wind_rose_500_use <- tempfile(fileext = ".png")
  png(filename = wind_rose_500_use, width = 4, height = 4, units = 'in', res = 300)
  plot(p500)
  dev.off()



  for_wind_rose_1000ha <- subset(dated_fires_intersected_all_fires,area_correct>=1000)
  for_wind_rose_1000ha$Area_ha <- as.numeric(for_wind_rose_1000ha$Area_ha)
  for_wind_rose_1000ha_meteo_fires_inside <- result_hours_final_df_wind_rose[result_hours_final_df_wind_rose$ID %in% for_wind_rose_1000ha$ID, ]

  if (nrow(for_wind_rose_1000ha_meteo_fires_inside)>0){
    p1000 <- plot_windrose(spd = for_wind_rose_1000ha_meteo_fires_inside$WS,
                           dir = for_wind_rose_1000ha_meteo_fires_inside$WD,
                           spdseq = c(0,3,6,12,20,ceiling(max(for_wind_rose_0ha_meteo_fires_inside$WS))))
  } else {
    p1000 <- ggplot() +
      annotate("text", x = 0.5,  y = 0.5,
               size = 3,
               label = "No fire events with more than \n 1,000 ha burned recorded") + theme_void()
  }



  wind_rose_1000_use <- tempfile(fileext = ".png")
  png(filename = wind_rose_1000_use, width = 4, height = 4, units = 'in', res = 300)
  plot(p1000)
  dev.off()



  wind_rose_all <- ggarrange(p0,p100,p500,p1000,
                             labels = c("A", "B", "C","D"),
                             ncol = 2, nrow = 2, common.legend = TRUE,legend="bottom")


  wind_rose_all_use <- tempfile(fileext = ".png")
  png(filename = wind_rose_all_use, width = 5, height = 6, units = 'in', res = 300)
  plot(wind_rose_all)
  dev.off()



  #Build the report as a word file


  if (create.clusters == TRUE){
    meteo1_use <- round(meteo1[,c("cluster","temperature_use","HR_use","WS_use", "size","mean_area_ha", "per95_area_ha" )],0)
    meteo2_use <- round(meteo2[,c("cluster","temperature_use","HR_use","WS_use", "size","mean_area_ha", "per95_area_ha")],0)
    meteo3_use <- round(meteo3[,c("cluster","temperature_use","HR_use","WS_use", "size","mean_area_ha", "per95_area_ha")],0)
    meteo4_use <- round(meteo4[,c("cluster","temperature_use","HR_use","WS_use", "size","mean_area_ha", "per95_area_ha")],0)
    meteo5_use <- round(meteo5[,c("cluster","temperature_use","HR_use","WS_use", "size","mean_area_ha", "per95_area_ha")],0)
    meteo6_use <- round(meteo6[,c("cluster","temperature_use","HR_use","WS_use","size","mean_area_ha", "per95_area_ha")],0)
    meteo7_use <- round(meteo7[,c("cluster","temperature_use","HR_use","WS_use", "size","mean_area_ha", "per95_area_ha")],0)
    meteo8_use <- round(meteo8[,c("cluster","temperature_use","HR_use","WS_use", "size","mean_area_ha", "per95_area_ha")],0)
    meteo9_use <- round(meteo9[,c("cluster","temperature_use","HR_use","WS_use", "size","mean_area_ha", "per95_area_ha")],0)
    meteo10_use <- round(meteo10[,c("cluster","temperature_use","HR_use","WS_use", "size","mean_area_ha", "per95_area_ha")],0)



    meteo1_use$freq <- round(meteo1_use$size/sum(meteo1_use$size),2)

    meteo2_use$freq <- round(meteo2_use$size/sum(meteo2_use$size),2)
    meteo3_use$freq <- round(meteo3_use$size/sum(meteo3_use$size),2)
    meteo4_use$freq <- round(meteo4_use$size/sum(meteo4_use$size),2)
    meteo5_use$freq <- round(meteo5_use$size/sum(meteo5_use$size),2)
    meteo6_use$freq <- round(meteo6_use$size/sum(meteo6_use$size),2)
    meteo7_use$freq <- round(meteo7_use$size/sum(meteo7_use$size),2)
    meteo8_use$freq <- round(meteo8_use$size/sum(meteo8_use$size),2)
    meteo9_use$freq <- round(meteo9_use$size/sum(meteo9_use$size),2)
    meteo10_use$freq <- round(meteo10_use$size/sum(meteo10_use$size),2)


    names(meteo1_use)[names(meteo1_use) == 'size'] <- 'Cluster size'
    names(meteo1_use)[names(meteo1_use) == 'freq'] <- 'Cluster RF'
    names(meteo1_use)[names(meteo1_use) == 'temperature_use'] <- 'T'
    names(meteo1_use)[names(meteo1_use) == 'HR_use'] <- 'RH'
    names(meteo1_use)[names(meteo1_use) == 'WS_use'] <- 'WS'
    names(meteo1_use)[names(meteo1_use) == 'mean_area_ha'] <- 'Avg. Fire Size'
    names(meteo1_use)[names(meteo1_use) == 'per95_area_ha'] <- 'P95 Fire Size'


    names(meteo2_use)[names(meteo2_use) == 'size'] <- 'Cluster size'
    names(meteo2_use)[names(meteo2_use) == 'freq'] <- 'Cluster RF'
    names(meteo2_use)[names(meteo2_use) == 'temperature_use'] <- 'T'
    names(meteo2_use)[names(meteo2_use) == 'HR_use'] <- 'RH'
    names(meteo2_use)[names(meteo2_use) == 'WS_use'] <- 'WS'
    names(meteo2_use)[names(meteo2_use) == 'mean_area_ha'] <- 'Avg. Fire Size'
    names(meteo2_use)[names(meteo2_use) == 'per95_area_ha'] <- 'P95 Fire Size'

    names(meteo3_use)[names(meteo3_use) == 'size'] <- 'Cluster size'
    names(meteo3_use)[names(meteo3_use) == 'freq'] <- 'Cluster RF'
    names(meteo3_use)[names(meteo3_use) == 'temperature_use'] <- 'T'
    names(meteo3_use)[names(meteo3_use) == 'HR_use'] <- 'RH'
    names(meteo3_use)[names(meteo3_use) == 'WS_use'] <- 'WS'
    names(meteo3_use)[names(meteo3_use) == 'mean_area_ha'] <- 'Avg. Fire Size'
    names(meteo3_use)[names(meteo3_use) == 'per95_area_ha'] <- 'P95 Fire Size'

    names(meteo4_use)[names(meteo4_use) == 'size'] <- 'Cluster size'
    names(meteo4_use)[names(meteo4_use) == 'freq'] <- 'Cluster RF'
    names(meteo4_use)[names(meteo4_use) == 'temperature_use'] <- 'T'
    names(meteo4_use)[names(meteo4_use) == 'HR_use'] <- 'RH'
    names(meteo4_use)[names(meteo4_use) == 'WS_use'] <- 'WS'
    names(meteo4_use)[names(meteo4_use) == 'mean_area_ha'] <- 'Avg. Fire Size'
    names(meteo4_use)[names(meteo4_use) == 'per95_area_ha'] <- 'P95 Fire Size'

    names(meteo5_use)[names(meteo5_use) == 'size'] <- 'Cluster size'
    names(meteo5_use)[names(meteo5_use) == 'freq'] <- 'Cluster RF'
    names(meteo5_use)[names(meteo5_use) == 'temperature_use'] <- 'T'
    names(meteo5_use)[names(meteo5_use) == 'HR_use'] <- 'RH'
    names(meteo5_use)[names(meteo5_use) == 'WS_use'] <- 'WS'
    names(meteo5_use)[names(meteo5_use) == 'mean_area_ha'] <- 'Avg. Fire Size'
    names(meteo5_use)[names(meteo5_use) == 'per95_area_ha'] <- 'P95 Fire Size'

    names(meteo6_use)[names(meteo6_use) == 'size'] <- 'Cluster size'
    names(meteo6_use)[names(meteo6_use) == 'freq'] <- 'Cluster RF'
    names(meteo6_use)[names(meteo6_use) == 'temperature_use'] <- 'T'
    names(meteo6_use)[names(meteo6_use) == 'HR_use'] <- 'RH'
    names(meteo6_use)[names(meteo6_use) == 'WS_use'] <- 'WS'
    names(meteo6_use)[names(meteo6_use) == 'mean_area_ha'] <- 'Avg. Fire Size'
    names(meteo6_use)[names(meteo6_use) == 'per95_area_ha'] <- 'P95 Fire Size'

    names(meteo7_use)[names(meteo7_use) == 'size'] <- 'Cluster size'
    names(meteo7_use)[names(meteo7_use) == 'freq'] <- 'Cluster RF'
    names(meteo7_use)[names(meteo7_use) == 'temperature_use'] <- 'T'
    names(meteo7_use)[names(meteo7_use) == 'HR_use'] <- 'RH'
    names(meteo7_use)[names(meteo7_use) == 'WS_use'] <- 'WS'
    names(meteo7_use)[names(meteo7_use) == 'mean_area_ha'] <- 'Avg. Fire Size'
    names(meteo7_use)[names(meteo7_use) == 'per95_area_ha'] <- 'P95 Fire Size'

    names(meteo8_use)[names(meteo8_use) == 'size'] <- 'Cluster size'
    names(meteo8_use)[names(meteo8_use) == 'freq'] <- 'Cluster RF'
    names(meteo8_use)[names(meteo8_use) == 'temperature_use'] <- 'T'
    names(meteo8_use)[names(meteo8_use) == 'HR_use'] <- 'RH'
    names(meteo8_use)[names(meteo8_use) == 'WS_use'] <- 'WS'
    names(meteo8_use)[names(meteo8_use) == 'mean_area_ha'] <- 'Avg. Fire Size'
    names(meteo8_use)[names(meteo8_use) == 'per95_area_ha'] <- 'P95 Fire Size'

    names(meteo9_use)[names(meteo9_use) == 'size'] <- 'Cluster size'
    names(meteo9_use)[names(meteo9_use) == 'freq'] <- 'Cluster RF'
    names(meteo9_use)[names(meteo9_use) == 'temperature_use'] <- 'T'
    names(meteo9_use)[names(meteo9_use) == 'HR_use'] <- 'RH'
    names(meteo9_use)[names(meteo9_use) == 'WS_use'] <- 'WS'
    names(meteo9_use)[names(meteo9_use) == 'mean_area_ha'] <- 'Avg. Fire Size'
    names(meteo9_use)[names(meteo9_use) == 'per95_area_ha'] <- 'P95 Fire Size'

    names(meteo10_use)[names(meteo10_use) == 'size'] <- 'Cluster size'
    names(meteo10_use)[names(meteo10_use) == 'freq'] <- 'Cluster RF'
    names(meteo10_use)[names(meteo10_use) == 'temperature_use'] <- 'T'
    names(meteo10_use)[names(meteo10_use) == 'HR_use'] <- 'RH'
    names(meteo10_use)[names(meteo10_use) == 'WS_use'] <- 'WS'
    names(meteo10_use)[names(meteo10_use) == 'mean_area_ha'] <- 'Avg. Fire Size'
    names(meteo10_use)[names(meteo10_use) == 'per95_area_ha'] <- 'P95 Fire Size'


    if(length(unique(mc$classification))>1){
      plot_uncer_modbas_src <- uncer_modbas
      plot_uncer_modbas_width <- 5
      plot_uncer_modbas_height <- 6
      plot_uncer_modbas_style<-"centered"
    } else {

      plot_uncer_modbas_src <- pt_study_use
      plot_uncer_modbas_width <- 0.01
      plot_uncer_modbas_height <- 0.01
      plot_uncer_modbas_style<-"centered"
    }

  } else {
    all_percentiles_use <- all_percentiles

    names(all_percentiles_use)[names(all_percentiles_use) == 'temperature_use'] <- 'T'
    names(all_percentiles_use)[names(all_percentiles_use) == 'HR_use'] <- 'RH'
    names(all_percentiles_use)[names(all_percentiles_use) == 'WS_use'] <- 'WS'




  }



  my_doc <- read_docx()

  setwd(output.folder)



  if (active.period=='user') {
    write_it <- paste("Active period was defined by the user as the interval of the following hours:", user.period, sep=" ")}

  if (active.period=="energy") {
    write_it <- paste("Active period was defined by the average energy released during fire spread, which peaks from 12h to 20h (for more information contact Akli Benali: aklibenali@gmail.com)", sep=" ")}


  if (active.period=="all") {
    write_it <- paste("No active period was defined. All 24 hours of days with fire events were considered")}



  if (create.clusters==TRUE){

    my_doc <- my_doc %>%

      body_add_par("Conditions of the analysis", style = "heading 1") %>%
      body_add_par(paste("The following report was generated automatically by the 'MTTfireCAL' package. The results should be critically analyzed. For questions and comments please contact Bruno Aparicio (bruno.a.aparicio@gmail.com)"),style = "Normal") %>%
      body_add_par(paste("Please cite this package as Aparicio BA, Benali B, Sá A (2023) xxxxxxx"),style = "Normal") %>%
      body_add_par("") %>%
      body_add_par(paste("This report was generated using the following definitions: "),style = "Normal") %>%

      body_add_par(write_it,style = "Normal") %>%
      body_add_par(paste(""),style = "Normal") %>%

      body_add_par(paste("The analysis considered a minimum fire size of", min.size, "ha",sep=" "),style = "Normal") %>%
      body_add_par(paste(""),style = "Normal") %>%

      body_add_par(paste("The analysis considered only fire perimeters with at least ", min.overlap, "% of their area inside the study area",sep=""),style = "Normal") %>%
      body_add_par(paste(""),style = "Normal") %>%

      body_add_par("Fire regime analysis", style = "heading 1") %>%
      body_add_par(paste("For the selected study area and using the conditions above, the total number of fire events used for the characterization of fire size distribution was ", n_fires_considered,". From these, ",length(unique(meteo_fires_inside$ID))," fires are dated and were used to extract the meteorological conditions during fire spread.", sep=""),style = "Normal") %>%
      body_add_par(paste("Because the user defined the fire.aggregation as ", fire.aggregation," and the meteorological aggregation as ",meteo.aggregation, " the total number of meteorological data used for the meteorological clustering process is ",nrow(meteo_fires_inside),".", sep=""),style = "Normal") %>%
      body_add_par(paste(""),style = "Normal") %>%


      body_add_par("") %>%
      body_add_par(paste("The figure below illustrates the location of the study area in Portugal (in black)"),style = "Normal") %>%
      body_add_par("") %>%
      body_add_img(src = pt_study_use, width = 4, height = 6, style = "centered") %>%





      body_add_par("") %>%
      body_add_par(paste("The figure below illustrates the fire size distribution for the considered period in the study area"),style = "Normal") %>%
      body_add_par("") %>%
      body_add_img(src = size_dist_use, width = 6, height = 4, style = "centered") %>%
      body_add_par("") %>%

      body_add_par(paste("The figure below illustrates the burned area per year in hectares (barplot) and the cumulative burned area as percentage (line) for the considered period in the study area"),style = "Normal") %>%
      body_add_par("")%>%
      body_add_img(src = BA_dist_use, width = 6, height = 4, style = "centered") %>%
      body_add_par("")%>%

      body_add_par(paste("The figure below illustrates the contribution of burned area in each fire size class to the overall burned area. For instance, fires that burned less than 100 ha contributed with ", round(table_for_graph[1,1],0),"% to the total burned area; fires that burned between 100 and 500 ha contributed with ", round(table_for_graph[2,1],0),"% to the total burned area, etc. The fire size classes are in hectares",sep=""),style = "Normal") %>%
      body_add_par("")%>%
      body_add_img(src = plot_burned_area_per_class_use, width = 6, height = 4, style = "centered") %>%
      body_add_par("")%>%


      body_add_par("Fire weather analysis", style = "heading 1") %>%
      body_add_par("")%>%
      body_add_par(paste("The figure below illustrates the wind roses considering the days with fire occurrence"),style = "Normal") %>%
      body_add_par("")%>%
      body_add_img(src = wind_rose_all_use, width = 5, height = 6, style = "centered") %>%
      body_add_par("")%>%
      body_add_par(paste("A - Considering fire size > 0 ha; B - Considering fire size > 100 ha; C - Considering fire size > 500 ha; D - Considering fire size > 1000 ha"),style = "Normal") %>%


      body_add_par("")%>%
      body_add_par("Cluster analysis", style = "heading 2") %>%

      body_add_par(paste("Model-based cluster analysis (MBCA) was created to automatize the demanding model-selection procedure of traditional explorative clustering methods (e. g., hierarchical and k-means clustering). For a proper understanding of the outputs interpretation please see Stahl and Sallis, 2012 (https://doi.org/10.1002/wics.1204)."),style = "Normal") %>%
      body_add_par("")%>%
      body_add_par(paste("The figure below illustrates the Bayesian Information Criterion (BIC) to evaluate model appropriateness regarding the optimal number of clusters. In this particular case, model-based clustering indicates",optimal_mbc,"as the optimal number of clusters"),style = "Normal") %>%
      body_add_par("", style = "Normal") %>%
      body_add_img(src = BIC_modbas, width = 5, height = 6, style = "centered") %>%
      body_add_par("", style = "Normal") %>%

      body_add_img(src = plot_uncer_modbas_src, width = plot_uncer_modbas_width, height = plot_uncer_modbas_height, style = "centered") %>%
      body_add_par("", style = "Normal") %>%

      body_add_par("Mean value (centroid) of each meteorological cluster", style = "heading 3") %>% # blank paragraph
      body_add_par("")%>%
      body_add_table(meteo1_use, style = "table_template") %>%
      body_add_par("")%>%
      body_add_par(paste("T represents the average temperature in each cluster; RH represents the average relative humidity in each cluster; WS represents average wind speed in each cluster; FWI represents the average FWI in each cluster; Cluster size represents the absolute size of the cluster (number of fire weathers in each cluster); Avg. Fire size represents the average fire size for fire events in each cluster; P95 Fire size represents the Percentile 95 of the fire size for fire events in each cluster; and Cluster RF represents the relative frequency of each cluster."),style = "Normal") %>%
      body_add_par("")%>%


      body_add_par("K-means classification", style = "heading 2") %>%
      body_add_par("")%>%
      body_add_par(paste("Kmeans algorithm is an iterative algorithm that tries to partition the dataset into K pre-defined distinct non-overlapping clusters. It assigns data points to a cluster such that it minimizes the sum of the squared distance between the data points and the cluster's centroid (arithmetic mean). A lower variation represents a more homogeneous cluster. For more details on k-means clustering algorithm please refer to Likas et al. 2003 (https://doi.org/10.1016/S0031-3203(02)00060-2) and to Kodinariya and Makwana (2013). Review on determining number of Cluster in K-Means Clustering"),style = "Normal") %>%
      body_add_par("")%>%
      body_add_img(src = kmeans_all_use, width = 5, height = 6, style = "centered") %>%
      body_add_par(paste("The silhouette value is a measure of how similar an object is to its own cluster (cohesion) compared to other clusters (separation). The silhouette ranges from -1 to +1, where a high value indicates that the object is well matched to its own cluster and poorly matched to neighboring clusters. If most objects have a high value, then the clustering configuration is appropriate. If many points have a low or negative value, then the clustering configuration may have too many or too few clusters."),style = "Normal") %>%



      body_add_img(src = silhouette_use, width = 6, height = 4, style = "centered") %>%
      body_add_par(paste(""),style = "Normal") %>%

      body_add_img(src = elbow_use, width = 6, height = 4, style = "centered") %>%
      body_add_par(paste("The elbow method calculates the Within-Cluster-Sum of Squared Errors (WSS) for different values of k, and choose the k for which WSS first starts to diminish at a lower rate (smaller slope). The optimal number of clusters is found at the elbow, i.e. the point after which the total within sum of square starts to decrease in a linear way"),style = "Normal") %>%
      body_add_par(paste(""),style = "Normal") %>%



      body_add_par("",style = "Normal") %>%
      body_add_par("",style = "Normal") %>%
      body_add_par("Mean value (centroid) of each meteorological cluster", style = "heading 3") %>%
      body_add_par("")%>%
      body_add_table(meteo2_use, style = "table_template") %>%
      body_add_par("", style = "Normal") %>%
      body_add_table(meteo3_use, style = "table_template") %>%
      body_add_par("", style = "Normal") %>%
      body_add_table(meteo4_use, style = "table_template") %>%
      body_add_par("", style = "Normal") %>%
      body_add_table(meteo5_use, style = "table_template") %>%
      body_add_par("", style = "Normal") %>%
      body_add_table(meteo6_use, style = "table_template") %>%
      body_add_par("", style = "Normal") %>%
      body_add_table(meteo7_use, style = "table_template") %>%
      body_add_par("", style = "Normal") %>%
      body_add_table(meteo8_use, style = "table_template") %>%
      body_add_par("", style = "Normal") %>%
      body_add_table(meteo9_use, style = "table_template") %>%
      body_add_par("", style = "Normal") %>%
      body_add_table(meteo10_use, style = "table_template") %>%

      body_add_par("",style = "Normal") %>%
      body_add_par("",style = "Normal") %>%
      body_add_par("Number of durations to consider", style = "heading 1") %>%
      body_add_par(paste("The figure below represents the identification of peaks in the distribution of fire size. The vertical red lines represent the number of peaks in the distribution of the fire size classes. There are",nrow(spike_detected_use),"recommended to use in the calibration to better reproduce the historical pattern of fire size distribution. For example, the first duration should represent fires with size between",freqs_my_fires_t_inter_intersected_spikes$first_val[spike_detected_use[1,1]],"and",freqs_my_fires_t_inter_intersected_spikes$first_val[spike_detected_use[2,1]], "hectares.",sep=" "),style = "Normal")%>%
      body_add_par("",style = "Normal") %>%
      body_add_img(src = size_dist_spike_use, width = 6, height = 4, style = "centered")




    print(my_doc, target = "Automatic report.docx")

  } else {

    my_doc <- my_doc %>%


      body_add_par("Conditions of the analysis", style = "heading 1") %>%
      body_add_par(paste("The following report was generated automatically by the 'MTTfireCAL' package. The results should be critically analyzed. For questions and comments please contact Bruno Aparicio (bruno.a.aparicio@gmail.com)"),style = "Normal") %>%
      body_add_par(paste("Please cite this package as Aparicio BA, Benali B, Sá A (2023) xxxxxxx"),style = "Normal") %>%
      body_add_par("") %>%
      body_add_par(paste("This report was generated using the following definitions: "),style = "Normal") %>%

      body_add_par(write_it,style = "Normal") %>%
      body_add_par(paste(""),style = "Normal") %>%

      body_add_par(paste("The analysis considered a minimum fire size of", min.size, "ha",sep=" "),style = "Normal") %>%
      body_add_par(paste(""),style = "Normal") %>%

      body_add_par(paste("The analysis considered only fire perimeters with at least ", min.overlap, "% of their area inside the study area",sep=""),style = "Normal") %>%
      body_add_par(paste(""),style = "Normal") %>%

      body_add_par("Fire regime analysis", style = "heading 1") %>%
      body_add_par(paste("For the selected study area and using the conditions above, the total number of fire events used for the characterization of fire size distribution was ", n_fires_considered,". From these, ",length(unique(meteo_fires_inside$ID))," fires are dated and were used to extract the meteorological conditions during fire spread.", sep=""),style = "Normal") %>%
      body_add_par(paste("Because the user defined the fire.aggregation as ", fire.aggregation," and the meteorological aggregation as ",meteo.aggregation, " the total number of meteorological data used for the meteorological clustering process is ",nrow(meteo_fires_inside),".", sep=""),style = "Normal") %>%
      body_add_par(paste(""),style = "Normal") %>%


      body_add_par("") %>%
      body_add_par(paste("The figure below illustrates the location of the study area in Portugal (in black)"),style = "Normal") %>%
      body_add_par("") %>%
      body_add_img(src = pt_study_use, width = 4, height = 6, style = "centered") %>%





      body_add_par("") %>%
      body_add_par(paste("The figure below illustrates the fire size distribution for the considered period in the study area"),style = "Normal") %>%
      body_add_par("") %>%
      body_add_img(src = size_dist_use, width = 6, height = 4, style = "centered") %>%
      body_add_par("") %>%

      body_add_par(paste("The figure below illustrates the burned area per year in hectares (barplot) and the cumulative burned area as percentage (line) for the considered period in the study area"),style = "Normal") %>%
      body_add_par("")%>%
      body_add_img(src = BA_dist_use, width = 6, height = 4, style = "centered") %>%
      body_add_par("")%>%

      body_add_par(paste("The figure below illustrates the contribution of burned area in each fire size class to the overall burned area."),style = "Normal") %>%
      body_add_par("")%>%
      body_add_img(src = plot_burned_area_per_class_use, width = 6, height = 4, style = "centered") %>%
      body_add_par("")%>%


      body_add_par("Fire weather analysis", style = "heading 1") %>%
      body_add_par("")%>%
      body_add_par(paste("The figure below illustrates the wind roses considering the days with fire occurrence"),style = "Normal") %>%
      body_add_par("")%>%
      body_add_img(src = wind_rose_all_use, width = 5, height = 6, style = "centered") %>%
      body_add_par("")%>%
      body_add_par(paste("A - Considering fire size > 0 ha; B - Considering fire size > 100 ha; C - Considering fire size > 500 ha; D - Considering fire size > 1000 ha"),style = "Normal") %>%




      #model-based clustering
      body_add_par("")%>%
      body_add_par("Characterization of weather conditions - Percentiles", style = "heading 2") %>%


      body_add_par("",style = "Normal") %>%

      body_add_table(all_percentiles_use, style = "table_template") %>%
      body_add_par("", style = "Normal") %>%


      body_add_par("",style = "Normal") %>%
      body_add_par("Number of durations to consider", style = "heading 1") %>%
      body_add_par(paste("The figure below represents the identification of peaks in the distribution of fire size. The vertical red lines represent the number of peaks in the distribution of the fire size classes. There are",nrow(spike_detected_use),"recommended to use in the calibration to better reproduce the historical pattern of fire size distribution. For example, the first duration should represent fires with size between",freqs_my_fires_t_inter_intersected_spikes$first_val[spike_detected_use[1,1]],"and",freqs_my_fires_t_inter_intersected_spikes$first_val[spike_detected_use[2,1]], "hectares.",sep=" "),style = "Normal")%>%
      body_add_par("",style = "Normal") %>%
      body_add_img(src = size_dist_spike_use, width = 6, height = 4, style = "centered")



    print(my_doc, target = "Automatic report.docx")

  }


  meteo_fires_inside$cluster_id_MB

  mainDir<- output.folder

  setwd(file.path(mainDir))
  write.csv(table_to_summary,"summary meteorology per fire event.csv",row.names = FALSE)
  write.csv(my_fires_t_inter_intersected_export,"summary fire size.csv",row.names = FALSE)






  if (create.clusters == TRUE){

    mainDir<- output.folder
    subDir <- "clusters_meteo"
    #create the csv file with cluster meteo data
    dir.create(file.path(mainDir, subDir), showWarnings = FALSE)
    setwd(file.path(mainDir, subDir))

    write.csv(meteo1_use,"model_based_clustering.csv",row.names = FALSE)
    write.csv(meteo2_use,"kmeans_2_clusters.csv",row.names = FALSE)
    write.csv(meteo3_use,"kmeans_3_clusters.csv",row.names = FALSE)
    write.csv(meteo4_use,"kmeans_4_clusters.csv",row.names = FALSE)
    write.csv(meteo5_use,"kmeans_5_clusters.csv",row.names = FALSE)
    write.csv(meteo6_use,"kmeans_6_clusters.csv",row.names = FALSE)
    write.csv(meteo7_use,"kmeans_7_clusters.csv",row.names = FALSE)
    write.csv(meteo8_use,"kmeans_8_clusters.csv",row.names = FALSE)
    write.csv(meteo9_use,"kmeans_9_clusters.csv",row.names = FALSE)
    write.csv(meteo10_use,"kmeans_10_clusters.csv",row.names = FALSE)


    write.csv(freqs_wd_MB_use,"model_based_clustering_wind_directions.csv",row.names = FALSE)
    write.csv(freqs_wd_km_2_use,"kmeans_2_clusters_wind_directions.csv",row.names = FALSE)
    write.csv(freqs_wd_km_3_use,"kmeans_3_clusters_wind_directions.csv",row.names = FALSE)
    write.csv(freqs_wd_km_4_use,"kmeans_4_clusters_wind_directions.csv",row.names = FALSE)
    write.csv(freqs_wd_km_5_use,"kmeans_5_clusters_wind_directions.csv",row.names = FALSE)
    write.csv(freqs_wd_km_6_use,"kmeans_6_clusters_wind_directions.csv",row.names = FALSE)
    write.csv(freqs_wd_km_7_use,"kmeans_7_clusters_wind_directions.csv",row.names = FALSE)
    write.csv(freqs_wd_km_8_use,"kmeans_8_clusters_wind_directions.csv",row.names = FALSE)
    write.csv(freqs_wd_km_9_use,"kmeans_9_clusters_wind_directions.csv",row.names = FALSE)
    write.csv(freqs_wd_km_10_use,"kmeans_10_clusters_wind_directions.csv",row.names = FALSE)


    mainDir<- output.folder
    subDir <- "final_freqs"
    #create the csv file with cluster meteo data
    dir.create(file.path(mainDir, subDir), showWarnings = FALSE)
    setwd(file.path(mainDir, subDir))

    write.csv(freqs_wd_MB,"model_based_clustering_final_freqs.csv",row.names = FALSE)
    write.csv(freqs_wd_km_2,"kmean_2_clusters_final_freqs.csv",row.names = FALSE)
    write.csv(freqs_wd_km_3,"kmean_3_clusters_final_freqs.csv",row.names = FALSE)
    write.csv(freqs_wd_km_4,"kmean_4_clusters_final_freqs.csv",row.names = FALSE)
    write.csv(freqs_wd_km_5,"kmean_5_clusters_final_freqs.csv",row.names = FALSE)
    write.csv(freqs_wd_km_6,"kmean_6_clusters_final_freqs.csv",row.names = FALSE)
    write.csv(freqs_wd_km_7,"kmean_7_clusters_final_freqs.csv",row.names = FALSE)
    write.csv(freqs_wd_km_8,"kmean_8_clusters_final_freqs.csv",row.names = FALSE)
    write.csv(freqs_wd_km_9,"kmean_9_clusters_final_freqs.csv",row.names = FALSE)
    write.csv(freqs_wd_km_10,"kmean_10_clusters_final_freqs.csv",row.names = FALSE)




    #Create the FMS files based on the clustering or percentiles process

    mainDir<- output.folder
    subDir <- "clusters_meteo"



    my_cluster_files <- list.files(path = paste(mainDir,subDir,sep="/"),pattern="clusters.csv|clustering.csv")

    setwd(file.path(mainDir,subDir))


    mc <- base::as.data.frame(1:256)
    colnames(mc) <- "mc"


    for(q in 1:length(my_cluster_files)){
      setwd(file.path(mainDir,subDir))
      my_cluster_loop <- read.csv(my_cluster_files[q])
      nome_usar <- my_cluster_files[q]

      nome_usar<- substr(nome_usar,1,nchar(nome_usar)-4)

      my_cluster_loop$HTR_1 <- round((4.37+0.161*my_cluster_loop$RH)-0.1*(my_cluster_loop$T -25)-0.027*my_cluster_loop$RH,0)
      my_cluster_loop$HTR_10 <- my_cluster_loop$HTR_1+1
      my_cluster_loop$HTR_100 <- my_cluster_loop$HTR_1+2

      my_cluster_loop$herbaceous <- 60
      my_cluster_loop$woody <- 90


      for (w in 1:nrow(my_cluster_loop)) {

        mainDir<- output.folder
        subDir_FMS <- "FMS_files"
        #create the csv file with cluster meteo data
        dir.create(file.path(mainDir, subDir_FMS), showWarnings = FALSE)
        setwd(file.path(mainDir, subDir_FMS))

        my_cluster_loop_vs2 <- my_cluster_loop[w,]
        my_cluster_loop_vs2 <- cbind(mc,my_cluster_loop_vs2)
        my_cluster_id <- my_cluster_loop_vs2[w,1]
        my_fms_loop <- my_cluster_loop_vs2[,c("mc","HTR_1","HTR_10","HTR_100","herbaceous","woody")]


        mainDir<- output.folder
        subDir_FMS_separate <- paste(subDir_FMS,nome_usar,sep="/")
        #create the csv file with cluster meteo data
        dir.create(file.path(mainDir, subDir_FMS_separate), showWarnings = FALSE)
        setwd(file.path(mainDir, subDir_FMS_separate))

        write.table(my_fms_loop,paste(nome_usar,"_",my_cluster_id,".fms",sep=""),col.names = FALSE,row.names = FALSE)
      }


    }

  } else {


    mainDir<- output.folder
    subDir <- "percentiles_meteo"
    #create the csv file with cluster meteo data
    dir.create(file.path(mainDir, subDir), showWarnings = FALSE)
    setwd(file.path(mainDir, subDir))


    write.csv(all_percentiles_use,"weather_percentiles.csv",row.names = FALSE)
    write.csv(percentile_wd_use,"weather_percentiles_wind_directions.csv",row.names = FALSE)

    percentile_wd_use_2 <- percentile_wd[,-3]
    percentile_wd_use_2$cluster_id <- 0


    percentile_wd_use_3 <- cbind(percentile_wd_use_2$cluster_id,percentile_wd_use_2[,1:(ncol(percentile_wd_use_2)-1)])

    names(percentile_wd_use_3)[names(percentile_wd_use_3) == 'percentile_wd_use_2$cluster_id'] <- 'cluster_id'

    for(i in 1:nrow(frequency_per_duration_class)){
      nome <- paste("duration_",i,sep="")
      percentile_wd_use_3[[nome]] <- percentile_wd_use_3$Freq*frequency_per_duration_class$sum[i]
    }


    mainDir<- output.folder
    subDir <- "final_freqs"
    #create the csv file with cluster meteo data
    dir.create(file.path(mainDir, subDir), showWarnings = FALSE)
    setwd(file.path(mainDir, subDir))

    write.csv(percentile_wd_use_3,"percentiles_final_freqs.csv",row.names = FALSE)

    #all_percentiles_wd

    mainDir<- output.folder
    subDir <- "percentiles_meteo"



    my_cluster_files <- list.files(path = paste(mainDir,subDir,sep="/"),pattern="percentile.csv|percentiles.csv")

    setwd(file.path(mainDir,subDir))


    mc <- base::as.data.frame(1:256)
    colnames(mc) <- "mc"


    for(q in 1:length(my_cluster_files)){
      setwd(file.path(mainDir,subDir))
      my_cluster_loop <- read.csv(my_cluster_files[q])
      nome_usar <- my_cluster_files[q]

      nome_usar<- substr(nome_usar,1,nchar(nome_usar)-4)

      my_cluster_loop$HTR_1 <- round((4.37+0.161*my_cluster_loop$RH)-0.1*(my_cluster_loop$T -25)-0.027*my_cluster_loop$RH,0)
      my_cluster_loop$HTR_10 <- my_cluster_loop$HTR_1+1
      my_cluster_loop$HTR_100 <- my_cluster_loop$HTR_1+2

      my_cluster_loop$herbaceous <- 60
      my_cluster_loop$woody <- 90


      for (w in 1:nrow(my_cluster_loop)) {

        mainDir<- output.folder
        subDir_FMS <- "FMS_files"
        #create the csv file with cluster meteo data
        dir.create(file.path(mainDir, subDir_FMS), showWarnings = FALSE)
        setwd(file.path(mainDir, subDir_FMS))

        my_cluster_loop_vs2 <- my_cluster_loop[w,]
        my_cluster_loop_vs2 <- cbind(mc,my_cluster_loop_vs2)
        my_cluster_id <- my_cluster_loop_vs2[w,2]
        my_fms_loop <- my_cluster_loop_vs2[,c("mc","HTR_1","HTR_10","HTR_100","herbaceous","woody")]


        mainDir<- output.folder
        subDir_FMS_separate <- paste(subDir_FMS,nome_usar,sep="/")
        #create the csv file with cluster meteo data
        dir.create(file.path(mainDir, subDir_FMS_separate), showWarnings = FALSE)
        setwd(file.path(mainDir, subDir_FMS_separate))

        write.table(my_fms_loop,paste(nome_usar,"_",my_cluster_id,".fms",sep=""),col.names = FALSE,row.names = FALSE)
      }


    }



  }

}
