#' Generates ignitions in the study area.
#' @description Generates ignitions in the study area that either follow a surface of probability of ignition (raster file) or are randomly allocated.
#' @param ign.raster Raster file with the probability of ignition.
#' @param IgnitionData Text file (csv) with the relative frequency of each meteorological cluster (or percentile) and duration to be simulated. If the function build_report was used in the process, then the file to be used should is stored in the folder final_freqs.
#' @param fuelmap Fuel map raster file. In alternative to using only one fuel map, the user might specify multiple fuel maps as a vector of characters.
#' @param nIgnitions Numeric. Total number of ignitions to be generated.
#' @param unburnable Numeric. Value of the fuel model(s) considered unburnable. Ignitions are prevented from being sampled in the fuel model(s) indicated.
#' @param LandCover.yr Numeric. Value (or vector of values) of the years of the fuel maps given as input in fuelmap.
#' @param LandCover.wgt Numeric. Value (or vector of values) of the weights of each fuel map in the fuelmap and LandCover.yr. The sum of the values must be 1.
#' @param shapeOut Binary. If 1, then a point shapefile is generated. If 0, only a text file with the coordinates of the ignitions is generated.
#' @param allow.zero Logical. If true, then a 0 percent probability of ignition is allowed in the raster file ign.raster. If false, then a minimum probability corresponding to the 5th percentile of the ign.raster is set. Default is false.
#' @param random.ignitions Logical. If true, then ignitions are generated randomly across the study area (excluding in the fuel model identified as unburnable). Default is false.
#' @param output.folder Path to the folder where the outputs should be saved.
#'
#' @return Returns text files with the coordinates of the ignitions in the correct format to be used in FConstMTT. One text file is generated by a combination of meteorological cluster, wind direction and duration class. A point shapefile per combination can also be generated.
#' @export
#' @import dplyr raster
#'
#' @examples
#' \dontrun{Gen_ign(ign.raster="C:/user/ignition.tif",
#' IgnitionData="C:/user/results/final_freqs/kmean_3_clusters_final_freqs.csv",
#' fuelmap=c("C:/user/fuelmap_2000.asc", "C:/user/fuelmap_2010.asc"),
#' nIgnitions=5000,
#' unburnable=c(98),
#' LandCover.yr=c(2000,2010),
#' LandCover.wgt=c(0.4,0.6),
#' shapeOut=1,
#' allow.zero=FALSE,
#' random.ignitions=FALSE,
#' output.folder="C:/user/results")}

Gen_ign <- function(ign.raster, IgnitionData, fuelmap, nIgnitions, unburnable, LandCover.yr, LandCover.wgt,
                    shapeOut, allow.zero, random.ignitions, output.folder) {

  replace<-TRUE
  prob<-TRUE

  if (missing(random.ignitions)) {
    random.ignitions <- FALSE }

  if (missing(allow.zero)) {
    allow.zero <- FALSE }


  if (random.ignitions==FALSE){
    x <- raster(ign.raster)
    val <- as.vector(x[[1]])}else{
      x <- raster(fuelmap[1])
      x<-reclassify(x,c(-Inf,Inf,1))
      val <- as.vector(x[[1]])
    }




  if(allow.zero==FALSE){


    minimum_val <- min(val[val > 0],na.rm=T)
    val[val < quantile(val[val > 0],0.01,na.rm=T)] <- quantile(val[val > 0],0.05,na.rm=T)
    x <- reclassify(x, c(-Inf,quantile(val[val > 0],0.05,na.rm=T),quantile(val[val > 0],0.05,na.rm=T)))

  }


  probs <-  val




  cellNum <- 1:raster::ncell(x)
  cellNum <- cellNum[!is.na(val)]

  probs <- probs[!is.na(val)]


  nfuelmaps <- length(fuelmap)

  unburnable_low <- (as.numeric(unburnable)-0.5)
  unburnable_high <- (as.numeric(unburnable)+0.5)

  datalist <- list()
  for(g in 1:nfuelmaps){
    fuelmap_n <- raster(fuelmap[g])

    for (w in 1:length(unburnable)){

      fuelmap_n <- reclassify(fuelmap_n, c(unburnable_low[w],unburnable_high[w],NA))}
    assign(paste("mc_use_",g,sep=""),fuelmap_n)

    datalist[g]<-paste0("mc_use_",g)

    x = resample(x, fuelmap_n, "bilinear")

  }

  x <- reclassify(x, c(-Inf,0,minimum_val))


  xx <- x+0


  Pattern1<-grep("mc_use_",datalist,value=TRUE)



  Pattern1_list<-do.call("list",mget(Pattern1))



  for (i in 1:length(Pattern1_list)) {
    Pattern1_list[[i]] <- resample(Pattern1_list[[i]], x, "bilinear")
  }



  if (nfuelmaps==1){
    rst1_mod <- overlay(xx, mc_use_1, fun = function(x, y) {
      x[is.na(y[])] <- NA
      return(x)
    })}


  if (nfuelmaps==2){

    rst1_mod <- overlay(xx, mc_use_1,mc_use_2, fun = function(x, y,z) {
      x[is.na(y[])] <- NA
      x[is.na(z[])] <- NA
      return(x)
    })}


  if (nfuelmaps==3){
    rst1_mod <- overlay(xx, mc_use_1,mc_use_2,mc_use_3, fun = function(x, y,z,k) {
      x[is.na(y[])] <- NA
      x[is.na(z[])] <- NA
      x[is.na(k[])] <- NA
      return(x)
    })}

  if (nfuelmaps==4){
    rst1_mod <- overlay(xx, mc_use_1,mc_use_2,mc_use_3,mc_use_4, fun = function(x, y,z,k,w) {
      x[is.na(y[])] <- NA
      x[is.na(z[])] <- NA
      x[is.na(k[])] <- NA
      x[is.na(w[])] <- NA
      return(x)
    })}




  my_ignitions<-read.csv(IgnitionData)

  nDurations <- length(grep(pattern = '^duration', x = colnames(my_ignitions), value = T))


  ndur <- length(grep(x = colnames(my_ignitions), pattern = "^duration"))



  lands <- as.data.frame(cbind(LandCover.yr,LandCover.wgt))
  colnames(lands)<- c("year","weight")


  original_size <- nrow(my_ignitions)


  results <- data.frame()

  for (q in 1:nrow(lands)) {
    my_ignitions$land_cover <- lands[q,1]
    my_ignitions$weight <- lands[q,2]
    results_pt <- my_ignitions
    results <- rbind(results,results_pt)
  }

  my_ignitions <- results

  for (o in 1:ndur) {
    nome_use <- paste("nign_dur_",o,sep="")

    for (q in 1:nrow(lands)) {
      my_ignitions[[paste("nign_dur_",o,sep="")]] <- round(my_ignitions[[paste("duration_",o,sep="")]]*my_ignitions$weight*nIgnitions)

    }}





  mainDir<- output.folder
  subDir_FMS <- "ignitions"
  #create the csv file with cluster meteo data
  dir.create(file.path(mainDir, subDir_FMS), showWarnings = FALSE)
  setwd(file.path(mainDir, subDir_FMS))


  colnames(my_ignitions)[1] <- "cluster"


  for (i in 1:nrow(my_ignitions)){

    if (nDurations >= 1){
      teste_duration_1 <- as.data.frame(Gen_ign_helper(rst1_mod, my_ignitions[i,"nign_dur_1"], replace = TRUE, prob = TRUE))
      direction_id <- my_ignitions[i,"WD_use"]
      cluster_id <- my_ignitions[i,"cluster"]
      land_cover_id <- my_ignitions[i,"land_cover"]

      if (nrow(teste_duration_1)>0){

        teste_duration_1_df <- as.data.frame(teste_duration_1)
        teste_duration_1_df$FIRE_NUM <- 1:nrow(teste_duration_1_df)
        colnames (teste_duration_1_df) <- c("XStart","YStart","FIRE_NUM")

        teste_duration_1_df_final <- as.data.frame(cbind(teste_duration_1_df$FIRE_NUM,teste_duration_1_df$XStart,teste_duration_1_df$YStart))
        colnames (teste_duration_1_df_final) <- c("FIRE_NUM", "XStart","YStart")

        write.table(teste_duration_1_df_final,paste("ignitions_","cluster_",cluster_id,"_duration_1_",direction_id,"_land_cover_",land_cover_id,".txt", sep=""),
                    row.names = F, sep=",")

        if (shapeOut==1){
          coordinates(teste_duration_1)=~x+y
          crs(teste_duration_1) <- crs(rst1_mod)
          raster::shapefile(teste_duration_1, paste("ignitions_","cluster_",cluster_id,"_duration_1_",direction_id,"_land_cover_",land_cover_id,".shp", sep=""))
        }


        }}



    if (nDurations >= 2){
      teste_duration_2 <- as.data.frame(Gen_ign_helper(rst1_mod, my_ignitions[i,"nign_dur_2"], replace = TRUE, prob = TRUE))
      direction_id <- my_ignitions[i,"WD_use"]
      cluster_id <- my_ignitions[i,"cluster"]
      land_cover_id <- my_ignitions[i,"land_cover"]


      if (nrow(teste_duration_2)>0){

        teste_duration_2_df <- as.data.frame(teste_duration_2)
        teste_duration_2_df$FIRE_NUM <- 1:nrow(teste_duration_2_df)
        colnames (teste_duration_2_df) <- c("XStart","YStart","FIRE_NUM")

        teste_duration_2_df_final <- as.data.frame(cbind(teste_duration_2_df$FIRE_NUM,teste_duration_2_df$XStart,teste_duration_2_df$YStart))
        colnames (teste_duration_2_df_final) <- c("FIRE_NUM", "XStart","YStart")

        write.table(teste_duration_2_df_final,paste("ignitions_","cluster_",cluster_id,"_duration_2_",direction_id,"_land_cover_",land_cover_id,".txt", sep=""),
                    row.names = F, sep=",")

        if (shapeOut==1){
          coordinates(teste_duration_2)=~x+y
          crs(teste_duration_2) <- crs(rst1_mod)
          raster::shapefile(teste_duration_2, paste("ignitions_","cluster_",cluster_id,"_duration_2_",direction_id,"_land_cover_",land_cover_id,".shp", sep=""))
        }


      }}




    if (nDurations >= 3){
      teste_duration_3 <- as.data.frame(Gen_ign_helper(rst1_mod, my_ignitions[i,"nign_dur_3"], replace = TRUE, prob = TRUE))
      direction_id <- my_ignitions[i,"WD_use"]
      cluster_id <- my_ignitions[i,"cluster"]
      land_cover_id <- my_ignitions[i,"land_cover"]



      if (nrow(teste_duration_3)>0){

        teste_duration_3_df <- as.data.frame(teste_duration_3)
        teste_duration_3_df$FIRE_NUM <- 1:nrow(teste_duration_3_df)
        colnames (teste_duration_3_df) <- c("XStart","YStart","FIRE_NUM")

        teste_duration_3_df_final <- as.data.frame(cbind(teste_duration_3_df$FIRE_NUM,teste_duration_3_df$XStart,teste_duration_3_df$YStart))
        colnames (teste_duration_3_df_final) <- c("FIRE_NUM", "XStart","YStart")

        write.table(teste_duration_3_df_final,paste("ignitions_","cluster_",cluster_id,"_duration_3_",direction_id,"_land_cover_",land_cover_id,".txt", sep=""),
                    row.names = F, sep=",")

        if (shapeOut==1){
          coordinates(teste_duration_3)=~x+y
          crs(teste_duration_3) <- crs(rst1_mod)
          raster::shapefile(teste_duration_3, paste("ignitions_","cluster_",cluster_id,"_duration_3_",direction_id,"_land_cover_",land_cover_id,".shp", sep=""))
        }

      }}



    if (nDurations >= 4){
      teste_duration_4 <- as.data.frame(Gen_ign_helper(rst1_mod, my_ignitions[i,"nign_dur_4"], replace = TRUE, prob = TRUE))
      direction_id <- my_ignitions[i,"WD_use"]
      cluster_id <- my_ignitions[i,"cluster"]
      land_cover_id <- my_ignitions[i,"land_cover"]


      if (nrow(teste_duration_4)>0){

        teste_duration_4_df <- as.data.frame(teste_duration_4)
        teste_duration_4_df$FIRE_NUM <- 1:nrow(teste_duration_4_df)
        colnames (teste_duration_4_df) <- c("XStart","YStart","FIRE_NUM")

        teste_duration_4_df_final <- as.data.frame(cbind(teste_duration_4_df$FIRE_NUM,teste_duration_4_df$XStart,teste_duration_4_df$YStart))
        colnames (teste_duration_4_df_final) <- c("FIRE_NUM", "XStart","YStart")

        write.table(teste_duration_4_df_final,paste("ignitions_","cluster_",cluster_id,"_duration_4_",direction_id,"_land_cover_",land_cover_id,".txt", sep=""),
                    row.names = F, sep=",")

        if (shapeOut==1){
          coordinates(teste_duration_4)=~x+y
          crs(teste_duration_4) <- crs(rst1_mod)
          raster::shapefile(teste_duration_4, paste("ignitions_","cluster_",cluster_id,"_duration_4_",direction_id,"_land_cover_",land_cover_id,".shp", sep=""))
        }


      }}



    if (nDurations >= 5){
      teste_duration_5 <- as.data.frame(Gen_ign_helper(rst1_mod, my_ignitions[i,"nign_dur_5"], replace = TRUE, prob = TRUE))
      direction_id <- my_ignitions[i,"WD_use"]
      cluster_id <- my_ignitions[i,"cluster"]
      land_cover_id <- my_ignitions[i,"land_cover"]

      if (nrow(teste_duration_5)>0){

        teste_duration_5_df <- as.data.frame(teste_duration_5)
        teste_duration_5_df$FIRE_NUM <- 1:nrow(teste_duration_5_df)
        colnames (teste_duration_5_df) <- c("XStart","YStart","FIRE_NUM")

        teste_duration_5_df_final <- as.data.frame(cbind(teste_duration_5_df$FIRE_NUM,teste_duration_5_df$XStart,teste_duration_5_df$YStart))
        colnames (teste_duration_5_df_final) <- c("FIRE_NUM", "XStart","YStart")

        write.table(teste_duration_5_df_final,paste("ignitions_","cluster_",cluster_id,"_duration_5_",direction_id,"_land_cover_",land_cover_id,".txt", sep=""),
                    row.names = F, sep=",")

        if (shapeOut==1){
          coordinates(teste_duration_5)=~x+y
          crs(teste_duration_5) <- crs(rst1_mod)
          raster::shapefile(teste_duration_5, paste("ignitions_","cluster_",cluster_id,"_duration_5_",direction_id,"_land_cover_",land_cover_id,".shp", sep=""))
        }

      }}




  }

  for (t in 1:nDurations){
    my_ignitions[[paste("duration_",t,sep="")]] <- my_ignitions[[paste("duration_",t,sep="")]]*my_ignitions$weight
  }


  write.table(my_ignitions,paste("clusters_freqs_final.csv", sep=""),
              row.names = F, sep=",")

}
