#' Create the inputs and runs FConstMTT from batch files
#' @description Uses the files generated by the functions build_report and Gen_ign to generate the input and batch files and to run FConstMTT.
#' @param Folder Path to the folder containing the bin folder with the FContMTT executable. This will also be the folder where the input and the batch files will be saved.
#' @param landscape Path to the folder contained the landscape file(s) to be used (either .tif or .lcp)
#' @param CrownFireMethod Numerical. Either 0 for the Finney's method, or 1 for use of Scott and Rheinhardt's method.
#' @param customfmd File containing the characterization of custom fuel models (.fmd file).
#' @param FmsFolder Path to the folder containing the fms file(s) to be use in the simulation.
#' @param Resolution Numeric. Represents the desired resolution of calculations.
#' @param GridDistanceUnits Numeric. Sets grid distance units, where 0 is for meters and 1 is for feet.
#' @param MeteoFile Text file containing the meteorological characterization of the clusters or percentiles to be used in the simulation.
#' @param Duration.1 Vector of values that define the interval of duration values to be tested in the first duration class. The vector must contain three values: c(from, to, by).
#' @param Duration.2 Optional. vector of values that define the interval of duration values to be tested in the second duration class. The vector must contain three values: c(from, to, by).
#' @param Duration.3 Optional. vector of values that define the interval of duration values to be tested in the third duration class. The vector must contain three values: c(from, to, by).
#' @param Duration.4 Optional. vector of values that define the interval of duration values to be tested in the fourth duration class. The vector must contain three values: c(from, to, by).
#' @param Duration.5 Optional. vector of values that define the interval of duration values to be tested in the fifth duration class. The vector must contain three values: c(from, to, by).
#' @param WS_unit Either kmh or mph.
#' @param FireListFile Path to the folder containing the ignitions to be used.
#' @param SpotProbability Numerical. Value to be used in the spot probability during the FConstMTT simulations.
#' @param output.folder Path to the folder where the outputs should be saved.
#' @param OutputFirePerims Binary. If 1, then the simulated fire perimeters are stored. If 0, then the simulated fire perimeters are not stored.
#' @param MetricFLP If 1, then the outputs of flame length probability (FLP file) are stored in meters. If 0, then the FLP files are stored in feet.
#' @param Run.fconstmtt Binary. If 1, then FConstMTT will automatically start running after creating the required files. If 0, then the .input and batch files are created but FConstMTT does not start running.
#'
#' @return Returns the input and batch files required to run FConstMTT for all the combinations to be tested. Optionally, FConstMTT might be run from R after the creation of the required files.
#' @export
#'
#' @examples
#' \dontrun{run_fconstmtt(Folder="C:/user",Folder.fconstmtt="C:/user/bin",landscape="C:/user/landscape_files",
#' CrownFireMethod=1,customfmd="C/user/my_fmd.fmd",
#' FmsFolder="C:/user/results/FMS_files/kmeans_3_clusters",
#' Resolution=100,GridDistanceUnits=0,
#' MeteoFile="C:/user/results/clusters_meteo/kmeans_3_clusters.csv",
#' Duration.1=c(min,max,by),
#' Duration.2=c(min,max,by),
#' Duration.3=c(min,max,by),
#' Duration.4=c(min,max,by),
#' Duration.5=c(min,max,by),
#' WS_unit="kmh",
#' FireListFile="C:/user/results/ignitions",SpotProbability=0.05,
#' OutputFirePerims=1,MetricFLP=0,
#' Run.fconstmtt=1)}
#'

run_fconstmtt <- function(Folder.fconstmtt,Folder,landscape,CrownFireMethod,
                          customfmd,FmsFolder,
                          Resolution,GridDistanceUnits,MeteoFile,
                          Duration.1,
                          Duration.2,
                          Duration.3,
                          Duration.4,
                          Duration.5,
                          WS_unit,
                          FireListFile,SpotProbability,
                          #output.folder,
                          OutputFirePerims,MetricFLP,
                          Run.fconstmtt) {

  landscape_correct <- list.files(landscape,pattern = ".tif$|.lcp$")
  CrownFireMethod_correct <- as.numeric(CrownFireMethod)
  customfmd_correct <- gsub("/", paste("\\\\"), customfmd)
  FmsFolder_correct <- list.files(FmsFolder,pattern = ".fms")

  Resolution_correct <- as.numeric(Resolution)
  GridDistanceUnits_correct <- as.numeric(GridDistanceUnits)

  NumFires_correct <- as.numeric(500)
  FireListFile_correct <- intersect(list.files(FireListFile,pattern = ".txt"), list.files(FireListFile,pattern = "ignitions"))

  SpotProbability_correct <- as.numeric(SpotProbability)
  ThreadsPerFire_correct <- as.numeric(1)
  #OutputsFolder_correct <-gsub("/", paste("\\\\"), output.folder)
  ProgressFilePathName_correct <- gsub("/", paste("\\\\"), "./fconstProgress.txt")
  OutputFirePerims_correct <- as.numeric (OutputFirePerims)
  MetricFLP_correct <- as.numeric(MetricFLP)
  IgnitionProbabilitySeed_correct <- as.numeric (42)



  V1 <- c("landscape:","CrownFireMethod:",
          "customfmd:","FmsFile:",
          "Resolution:","GridDistanceUnits:",
          "WindSpeed:","WindDirection:",
          "Duration:","NumFires:",
          "FireListFile:","SpotProbability:",
          "ThreadsPerFire:","OutputsName:",
          "ProgressFilePathName:","OutputFirePerims:",
          "MetricFLP:", "IgnitionProbabilitySeed:")





  if (missing(Duration.1)) {
    Duration.1_correct <- c(NA,NA,NA) } else {
      if (length(Duration.1)!=3) stop('The number of values in Duration.1 must be 3')
      if (Duration.1[2] < Duration.1[1]) stop('To must not be smaller than from in Duration.1')
      Duration.1_correct <- seq(from = Duration.1[1], to = Duration.1[2], by = Duration.1[3])
    }



  if (missing(Duration.2)) {
    Duration.2_correct <- c(NA,NA,NA) } else {
      if (length(Duration.2)!=3) stop('The number of values in Duration.2 must be 3')
      if (Duration.2[2] < Duration.2[1]) stop('To must not be smaller than from in Duration.2')
      Duration.2_correct <- seq(from = Duration.2[1], to = Duration.2[2], by = Duration.2[3])
    }



  if (missing(Duration.3)) {
    Duration.3_correct <- c(NA,NA,NA) } else {
      if (length(Duration.3)!=3) stop('The number of values in Duration.3 must be 3')
      if (Duration.3[2] < Duration.3[1]) stop('To must not be smaller than from in Duration.3')
      Duration.3_correct <- seq(from = Duration.3[1], to = Duration.3[2], by = Duration.3[3])
    }



  if (missing(Duration.4)) {
    Duration.4_correct <- c(NA,NA,NA) } else {
      if (length(Duration.4)!=3) stop('The number of values in Duration.4 must be 3')
      if (Duration.4[2] < Duration.4[1]) stop('To must not be smaller than from in Duration.4')
      Duration.4_correct <- seq(from = Duration.4[1], to = Duration.4[2], by = Duration.4[3])
    }



  if (missing(Duration.5)) {
    Duration.5_correct <- c(NA,NA,NA) } else {
      if (length(Duration.5)!=3) stop('The number of values in Duration.5 must be 3')
      if (Duration.5[2] < Duration.5[1]) stop('To must not be smaller than from in Duration.5')
      Duration.5_correct <- seq(from = Duration.5[1], to = Duration.5[2], by = Duration.5[3])
    }




  mainDir<- Folder
  subDir_FMS <- "inputs"
  subDir_outs <- "Outputs"
  dir.create(file.path(mainDir, subDir_outs), showWarnings = FALSE)
  dir.create(file.path(mainDir, subDir_FMS), showWarnings = FALSE)
  setwd(file.path(mainDir, subDir_FMS))

  OutputsFolder_correct <-file.path(mainDir, subDir_outs)
  OutputsFolder_correct <-gsub("/", paste("\\\\"), OutputsFolder_correct)


  FireListFile_correct_df <- as.data.frame(FireListFile_correct)


  FireListFile_correct_df <- FireListFile_correct_df[order(FireListFile_correct_df$FireListFile_correct),]
  FireListFile_correct_df <- as.data.frame(FireListFile_correct_df)


  if(is.logical(Duration.1_correct)==FALSE){
    FireListFile_correct_df_dur_1 <- FireListFile_correct_df[grep("duration_1", FireListFile_correct_df$FireListFile_correct), ]
    FireListFile_correct_df_dur_1 <- as.data.frame(FireListFile_correct_df_dur_1)
    n_durations1 <- length(Duration.1_correct)}else{
      FireListFile_correct_df_dur_1 <- NA
      n_durations1 <- 0
    }



  if(is.logical(Duration.2_correct)==FALSE){
    FireListFile_correct_df_dur_2 <- FireListFile_correct_df[grep("duration_2", FireListFile_correct_df$FireListFile_correct), ]
    FireListFile_correct_df_dur_2 <- as.data.frame(FireListFile_correct_df_dur_2)
    n_durations2 <- length(Duration.2_correct)}else{
      FireListFile_correct_df_dur_2 <- NA
      n_durations2 <- 0
    }

  if(is.logical(Duration.3_correct)==FALSE){
    FireListFile_correct_df_dur_3 <- FireListFile_correct_df[grep("duration_3", FireListFile_correct_df$FireListFile_correct), ]
    FireListFile_correct_df_dur_3 <- as.data.frame(FireListFile_correct_df_dur_3)
    n_durations3 <- length(Duration.3_correct)}else{
      FireListFile_correct_df_dur_3 <- NA
      n_durations3 <- 0
    }

  if(is.logical(Duration.4_correct)==FALSE){
    FireListFile_correct_df_dur_4 <- FireListFile_correct_df[grep("duration_4", FireListFile_correct_df$FireListFile_correct), ]
    FireListFile_correct_df_dur_4 <- as.data.frame(FireListFile_correct_df_dur_4)
    n_durations4 <- length(Duration.4_correct)}else{
      FireListFile_correct_df_dur_4 <- NA
      n_durations4 <- 0
    }

  if(is.logical(Duration.5_correct)==FALSE){
    FireListFile_correct_df_dur_5 <- FireListFile_correct_df[grep("duration_5", FireListFile_correct_df$FireListFile_correct), ]
    FireListFile_correct_df_dur_5 <- as.data.frame(FireListFile_correct_df_dur_5)
    n_durations5 <- length(Duration.5_correct)}else{
      FireListFile_correct_df_dur_5 <- NA
      n_durations5 <- 0
    }



  if(is.logical(Duration.1_correct)==FALSE){
    FireListFile_correct_df_dur_1_final <- FireListFile_correct_df_dur_1 %>% separate(FireListFile_correct_df_dur_1,
                                                                                      into=c("ignition", "cluster","cluster_name",
                                                                                             "duration","duration_name",
                                                                                             "direction","land","cover","land_cover_id"), sep="_")


    FireListFile_correct_df_dur_1_final$fullName <- FireListFile_correct_df_dur_1$FireListFile_correct_df_dur_1}  else{
      FireListFile_correct_df_dur_1_final<-NA
    }





  if(is.logical(Duration.2_correct)==FALSE){
    FireListFile_correct_df_dur_2_final <- FireListFile_correct_df_dur_2 %>% separate(FireListFile_correct_df_dur_2,
                                                                                      into=c("ignition", "cluster","cluster_name",
                                                                                             "duration","duration_name",
                                                                                             "direction","land","cover","land_cover_id"), sep="_")


    FireListFile_correct_df_dur_2_final$fullName <- FireListFile_correct_df_dur_2$FireListFile_correct_df_dur_2 }  else{
      FireListFile_correct_df_dur_2_final<-NA
    }




  if(is.logical(Duration.3_correct)==FALSE){
    FireListFile_correct_df_dur_3_final <- FireListFile_correct_df_dur_3 %>% separate(FireListFile_correct_df_dur_3,
                                                                                      into=c("ignition", "cluster","cluster_name",
                                                                                             "duration","duration_name",
                                                                                             "direction","land","cover","land_cover_id"), sep="_")



    FireListFile_correct_df_dur_3_final$fullName <- FireListFile_correct_df_dur_3$FireListFile_correct_df_dur_3}  else{
      FireListFile_correct_df_dur_3_final<-NA
    }



  if(is.logical(Duration.4_correct)==FALSE){
    FireListFile_correct_df_dur_4_final <- FireListFile_correct_df_dur_4 %>% separate(FireListFile_correct_df_dur_4,
                                                                                      into=c("ignition", "cluster","cluster_name",
                                                                                             "duration","duration_name",
                                                                                             "direction","land","cover","land_cover_id"), sep="_")



    FireListFile_correct_df_dur_4_final$fullName <- FireListFile_correct_df_dur_4$FireListFile_correct_df_dur_4} else{
      FireListFile_correct_df_dur_4_final<-NA
    }




  if(is.logical(Duration.5_correct)==FALSE){
    FireListFile_correct_df_dur_5_final <- FireListFile_correct_df_dur_5 %>% separate(FireListFile_correct_df_dur_5,
                                                                                      into=c("ignition", "cluster","cluster_name",
                                                                                             "duration","duration_name",
                                                                                             "direction","land","cover","land_cover_id"), sep="_")


    FireListFile_correct_df_dur_5_final$fullName <- FireListFile_correct_df_dur_5$FireListFile_correct_df_dur_5} else{
      FireListFile_correct_df_dur_5_final<-NA
    }



  FireListFile_correct_df_all_dur <- rbind(FireListFile_correct_df_dur_1_final, FireListFile_correct_df_dur_2_final,
                                           FireListFile_correct_df_dur_3_final,FireListFile_correct_df_dur_4_final,FireListFile_correct_df_dur_5_final)



  FireListFile_correct_df_all_dur <- FireListFile_correct_df_all_dur[rowSums(is.na(FireListFile_correct_df_all_dur)) != ncol(FireListFile_correct_df_all_dur), ]


  landscape_correct_df <- as.data.frame(landscape_correct)


  landscape_correct_df_final <- landscape_correct_df %>% separate(landscape_correct,
                                                                  into=c("land", "id" ), sep="_")


  landscape_correct_df_final$id<-gsub(".tif","",landscape_correct_df_final$id)
  landscape_correct_df_final$id<-gsub(".lcp","",landscape_correct_df_final$id)

  landscape_correct_df_final$LCPName <- landscape_correct_df$landscape_correct


  FireListFile_correct_df_all_dur$land_cover_id_final <- gsub(".txt","",FireListFile_correct_df_all_dur$land_cover_id)


  FireListFile_correct_df_all_dur <- left_join(FireListFile_correct_df_all_dur, landscape_correct_df_final, by=c("land_cover_id_final"="id"))



  FireListFile_correct_df_all_dur_all_all <- FireListFile_correct_df_all_dur %>% separate(fullName,
                                                                                          into=c("ignition", "cluster","cluster_name",
                                                                                                 "duration","duration_name",
                                                                                                 "direction","land","cover","land_cover_id"), sep="_")
  FireListFile_correct_df_all_dur_all_all$fullName <- FireListFile_correct_df_all_dur$fullName



  FmsFolder_correct_df <- as.data.frame(FmsFolder_correct)

  meteofile_use <- read.csv(MeteoFile)

  if (WS_unit=="kmh"){
    meteofile_use$WS <- round(meteofile_use$WS/1.609,0)
  }

  if (WS_unit=="mph"){
    meteofile_use$WS <- round(meteofile_use$WS,0)
  }


  first_word <- gsub("\\_.*","",FmsFolder_correct_df[1,1])

  if (first_word == "weather"){
    FmsFolder_correct_df_final <- FmsFolder_correct_df %>% separate(FmsFolder_correct,
                                                                    into=c("weather", "clusters","id"), sep="_")

  } else {


    FmsFolder_correct_df_final <- FmsFolder_correct_df %>% separate(FmsFolder_correct,
                                                                    into=c("cluster_type", "Nclusters","clusters","id"), sep="_")


  }

  FmsFolder_correct_df_final$id <- gsub(".fms","",FmsFolder_correct_df_final$id)
  FmsFolder_correct_df_final$full_name_fms <- FmsFolder_correct_df$FmsFolder_correct

  FmsFolder_correct_df_final$id <- as.numeric(FmsFolder_correct_df_final$id)

  FireListFile_correct_df_all_dur_all_all_not_fin<-left_join(meteofile_use,FmsFolder_correct_df_final, by=c("cluster"="id"))

  FireListFile_correct_df_all_dur_all_all$cluster_name<-as.numeric(FireListFile_correct_df_all_dur_all_all$cluster_name)

  FireListFile_correct_df_all_dur_all_all<-left_join(FireListFile_correct_df_all_dur_all_all,FireListFile_correct_df_all_dur_all_all_not_fin, by=c("cluster_name"="cluster"))




  FireListFile_correct_df_all_dur_all_all_dur1 <- subset(FireListFile_correct_df_all_dur_all_all,duration_name==1)
  FireListFile_correct_df_all_dur_all_all_dur2 <- subset(FireListFile_correct_df_all_dur_all_all,duration_name==2)
  FireListFile_correct_df_all_dur_all_all_dur3 <- subset(FireListFile_correct_df_all_dur_all_all,duration_name==3)
  FireListFile_correct_df_all_dur_all_all_dur4 <- subset(FireListFile_correct_df_all_dur_all_all,duration_name==4)
  FireListFile_correct_df_all_dur_all_all_dur5 <- subset(FireListFile_correct_df_all_dur_all_all,duration_name==5)


  FireListFile_correct_df_all_dur_all_all_dur1_use <- do.call("rbind", replicate(n_durations1, FireListFile_correct_df_all_dur_all_all_dur1, simplify = FALSE))
  FireListFile_correct_df_all_dur_all_all_dur2_use <- do.call("rbind", replicate(n_durations2, FireListFile_correct_df_all_dur_all_all_dur2, simplify = FALSE))
  FireListFile_correct_df_all_dur_all_all_dur3_use <- do.call("rbind", replicate(n_durations3, FireListFile_correct_df_all_dur_all_all_dur3, simplify = FALSE))
  FireListFile_correct_df_all_dur_all_all_dur4_use <- do.call("rbind", replicate(n_durations4, FireListFile_correct_df_all_dur_all_all_dur4, simplify = FALSE))
  FireListFile_correct_df_all_dur_all_all_dur5_use <- do.call("rbind", replicate(n_durations5, FireListFile_correct_df_all_dur_all_all_dur5, simplify = FALSE))


  FireListFile_correct_df_all_dur_all_all_use <- rbind(FireListFile_correct_df_all_dur_all_all_dur1_use,
                                                       FireListFile_correct_df_all_dur_all_all_dur2_use,
                                                       FireListFile_correct_df_all_dur_all_all_dur3_use,
                                                       FireListFile_correct_df_all_dur_all_all_dur4_use,
                                                       FireListFile_correct_df_all_dur_all_all_dur5_use)


  all_durations_test <- c(Duration.1_correct,Duration.2_correct,Duration.3_correct,Duration.4_correct,Duration.5_correct)


  dur_loop <- subset(FireListFile_correct_df_all_dur_all_all, duration_name == 1)


  if(!is.na(Duration.1_correct[1])){

    for(j in 1:length(Duration.1_correct)) {
      Duration_correct<- Duration.1_correct[j]


      for(k in 1:nrow(dur_loop)){
        FireListFile_correct_final <- dur_loop[k,"fullName"]
        Folder_right <- gsub("/", paste("\\\\"), Folder.fconstmtt)

        FireListFile_right <-gsub("/", paste("\\\\"), FireListFile)

        FireListFile_correct_final <- paste0(FireListFile_right,"\\",FireListFile_correct_final)

        WindDirection_correct <- dur_loop[k,"direction"]
        cluster_id <- as.numeric(dur_loop[k,"cluster_name"])
        land_cover_id <- dur_loop[k,"land_cover_id"]
        land_cover_id <- gsub(".txt","",land_cover_id)
        landscape_correct_loop <- dur_loop [k,"LCPName"]
        WindSpeed_correct <- dur_loop [k,"WS"]
        FmsFile_correct <- dur_loop [k,"full_name_fms"]

        landscape_correct_loop <- gsub(".tif.input","",landscape_correct_loop)

        landscape_name <- as.character(landscape_correct_loop)
        landscape_name <- gsub(".tif|.lcp", "", landscape_name)

        OutputsName_correct <- paste0(OutputsFolder_correct,"\\durval_",Duration_correct,"_cluster_",cluster_id,"_durclass_",1,"_",WindDirection_correct,"_land_cover_",land_cover_id,sep="")

        Folder_right <- gsub("/", paste("\\\\"), Folder.fconstmtt)
        Folder_right_landscape <- gsub("/", paste("\\\\"), landscape)
        landscape_correct_loop_full_name <- paste0(Folder_right_landscape,"\\",landscape_correct_loop)
        FmsFolder_right <- gsub("/", paste("\\\\"), FmsFolder)

        FmsFile_correct_full_name <- paste0(FmsFolder_right,"\\",FmsFile_correct)

        V2 <- rbind(landscape_correct_loop_full_name,CrownFireMethod_correct,
                    customfmd_correct,FmsFile_correct_full_name,
                    Resolution_correct,GridDistanceUnits_correct,
                    WindSpeed_correct,WindDirection_correct,
                    Duration_correct,NumFires_correct,
                    FireListFile_correct_final,SpotProbability_correct,
                    ThreadsPerFire_correct,OutputsName_correct,
                    ProgressFilePathName_correct,OutputFirePerims_correct,
                    MetricFLP_correct,IgnitionProbabilitySeed_correct)

        result <- cbind(V1,V2)

        nameInp<-paste0("durval_",Duration_correct,"_cluster_",cluster_id,"_land_cover_",land_cover_id,"_durclass_",1,"_",WindDirection_correct,".input",sep="")
        write.table(result, nameInp,
                    sep=" ",row.names = FALSE,col.names=FALSE, quote=FALSE)


        if (j==1 & k==1){
          all.nameInp <- nameInp
        } else {
          all.nameInp <- rbind (all.nameInp,nameInp)}

      }}
  }else{
    all.nameInp1 <- data.frame()
  }



  #dur 2

  dur_loop2 <- subset(FireListFile_correct_df_all_dur_all_all, duration_name == 2)

  if(!is.na(Duration.2_correct[1])){

    for(j in 1:length(Duration.2_correct)) {
      Duration_correct<- Duration.2_correct[j]





      for(k in 1:nrow(dur_loop2)){
        FireListFile_correct_final <- dur_loop2[k,"fullName"]
        Folder_right <- gsub("/", paste("\\\\"), Folder.fconstmtt)

        FireListFile_right <-gsub("/", paste("\\\\"), FireListFile)

        FireListFile_correct_final <- paste0(FireListFile_right,"\\",FireListFile_correct_final)

        WindDirection_correct <- dur_loop2[k,"direction"]
        cluster_id <- as.numeric(dur_loop2[k,"cluster_name"])
        land_cover_id <- dur_loop2[k,"land_cover_id"]
        land_cover_id <- gsub(".txt","",land_cover_id)
        landscape_correct_loop <- dur_loop2 [k,"LCPName"]
        WindSpeed_correct <- dur_loop2 [k,"WS"]
        FmsFile_correct <- dur_loop2 [k,"full_name_fms"]

        landscape_correct_loop <- gsub(".tif.input","",landscape_correct_loop)

        landscape_name <- as.character(landscape_correct_loop)

        OutputsName_correct <- paste0(OutputsFolder_correct,"\\durval_",Duration_correct,"_cluster_",cluster_id,"_durclass_",2,"_",WindDirection_correct,"_land_cover_",land_cover_id,sep="")


        Folder_right <- gsub("/", paste("\\\\"), Folder.fconstmtt)
        Folder_right_landscape <- gsub("/", paste("\\\\"), landscape)
        landscape_correct_loop_full_name <- paste0(Folder_right_landscape,"\\",landscape_correct_loop)
        FmsFolder_right <- gsub("/", paste("\\\\"), FmsFolder)

        FmsFile_correct_full_name <- paste0(FmsFolder_right,"\\",FmsFile_correct)

        V2 <- rbind(landscape_correct_loop_full_name,CrownFireMethod_correct,
                    customfmd_correct,FmsFile_correct_full_name,
                    Resolution_correct,GridDistanceUnits_correct,
                    WindSpeed_correct,WindDirection_correct,
                    Duration_correct,NumFires_correct,
                    FireListFile_correct_final,SpotProbability_correct,
                    ThreadsPerFire_correct,OutputsName_correct,
                    ProgressFilePathName_correct,OutputFirePerims_correct,
                    MetricFLP_correct,IgnitionProbabilitySeed_correct)

        result <- cbind(V1,V2)

        nameInp<-paste0("durval_",Duration_correct,"_cluster_",cluster_id,"_land_cover_",land_cover_id,"_durclass_",2,"_",WindDirection_correct,".input",sep="")
        write.table(result, nameInp,
                    sep=" ",row.names = FALSE,col.names=FALSE, quote=FALSE)


        if (j==1 & k==1){
          all.nameInp2 <- nameInp
        } else {
          all.nameInp2 <- rbind (all.nameInp2,nameInp)}

      }}
  }else{
    all.nameInp2 <- data.frame()
  }


  #dur 3

  dur_loop3 <- subset(FireListFile_correct_df_all_dur_all_all, duration_name == 3)

  if(!is.na(Duration.3_correct[1])){
    for(j in 1:length(Duration.3_correct)) {
      Duration_correct<- Duration.3_correct[j]


      for(k in 1:nrow(dur_loop3)){
        FireListFile_correct_final <- dur_loop3[k,"fullName"]
        Folder_right <- gsub("/", paste("\\\\"), Folder.fconstmtt)

        FireListFile_right <-gsub("/", paste("\\\\"), FireListFile)

        FireListFile_correct_final <- paste0(FireListFile_right,"\\",FireListFile_correct_final)

        WindDirection_correct <- dur_loop3[k,"direction"]
        cluster_id <- as.numeric(dur_loop3[k,"cluster_name"])
        land_cover_id <- dur_loop3[k,"land_cover_id"]
        land_cover_id <- gsub(".txt","",land_cover_id)
        landscape_correct_loop <- dur_loop3 [k,"LCPName"]
        WindSpeed_correct <- dur_loop3 [k,"WS"]
        FmsFile_correct <- dur_loop3 [k,"full_name_fms"]

        landscape_correct_loop <- gsub(".tif.input","",landscape_correct_loop)

        landscape_name <- as.character(landscape_correct_loop)

        OutputsName_correct <- paste0(OutputsFolder_correct,"\\durval_",Duration_correct,"_cluster_",cluster_id,"_durclass_",3,"_",WindDirection_correct,"_land_cover_",land_cover_id,sep="")

        Folder_right <- gsub("/", paste("\\\\"), Folder.fconstmtt)
        Folder_right_landscape <- gsub("/", paste("\\\\"), landscape)
        landscape_correct_loop_full_name <- paste0(Folder_right_landscape,"\\",landscape_correct_loop)
        FmsFolder_right <- gsub("/", paste("\\\\"), FmsFolder)

        FmsFile_correct_full_name <- paste0(FmsFolder_right,"\\",FmsFile_correct)

        V2 <- rbind(landscape_correct_loop_full_name,CrownFireMethod_correct,
                    customfmd_correct,FmsFile_correct_full_name,
                    Resolution_correct,GridDistanceUnits_correct,
                    WindSpeed_correct,WindDirection_correct,
                    Duration_correct,NumFires_correct,
                    FireListFile_correct_final,SpotProbability_correct,
                    ThreadsPerFire_correct,OutputsName_correct,
                    ProgressFilePathName_correct,OutputFirePerims_correct,
                    MetricFLP_correct,IgnitionProbabilitySeed_correct)

        result <- cbind(V1,V2)

        nameInp<-paste0("durval_",Duration_correct,"_cluster_",cluster_id,"_land_cover_",land_cover_id,"_durclass_",3,"_",WindDirection_correct,".input",sep="")
        write.table(result, nameInp,
                    sep=" ",row.names = FALSE,col.names=FALSE, quote=FALSE)


        if (j==1 & k==1){
          all.nameInp3 <- nameInp
        } else {
          all.nameInp3 <- rbind (all.nameInp3,nameInp)}

      }}
  }else{
    all.nameInp3 <- data.frame()
  }



  #dur 4

  dur_loop4 <- subset(FireListFile_correct_df_all_dur_all_all, duration_name == 4)

  if(!is.na(Duration.4_correct[1])){
    for(j in 1:length(Duration.4_correct)) {
      Duration_correct<- Duration.4_correct[j]



      for(k in 1:nrow(dur_loop4)){
        FireListFile_correct_final <- dur_loop4[k,"fullName"]
        Folder_right <- gsub("/", paste("\\\\"), Folder.fconstmtt)

        FireListFile_right <-gsub("/", paste("\\\\"), FireListFile)

        FireListFile_correct_final <- paste0(FireListFile_right,"\\",FireListFile_correct_final)

        WindDirection_correct <- dur_loop4[k,"direction"]
        cluster_id <- as.numeric(dur_loop4[k,"cluster_name"])
        land_cover_id <- dur_loop4[k,"land_cover_id"]
        land_cover_id <- gsub(".txt","",land_cover_id)
        landscape_correct_loop <- dur_loop4 [k,"LCPName"]
        WindSpeed_correct <- dur_loop4 [k,"WS"]
        FmsFile_correct <- dur_loop4 [k,"full_name_fms"]

        landscape_correct_loop <- gsub(".tif.input","",landscape_correct_loop)

        landscape_name <- as.character(landscape_correct_loop)

        OutputsName_correct <- paste0(OutputsFolder_correct,"\\durval_",Duration_correct,"_cluster_",cluster_id,"_durclass_",4,"_",WindDirection_correct,"_land_cover_",land_cover_id,sep="")

        Folder_right <- gsub("/", paste("\\\\"), Folder.fconstmtt)
        Folder_right_landscape <- gsub("/", paste("\\\\"), landscape)
        landscape_correct_loop_full_name <- paste0(Folder_right_landscape,"\\",landscape_correct_loop)
        FmsFolder_right <- gsub("/", paste("\\\\"), FmsFolder)

        FmsFile_correct_full_name <- paste0(FmsFolder_right,"\\",FmsFile_correct)

        V2 <- rbind(landscape_correct_loop_full_name,CrownFireMethod_correct,
                    customfmd_correct,FmsFile_correct_full_name,
                    Resolution_correct,GridDistanceUnits_correct,
                    WindSpeed_correct,WindDirection_correct,
                    Duration_correct,NumFires_correct,
                    FireListFile_correct_final,SpotProbability_correct,
                    ThreadsPerFire_correct,OutputsName_correct,
                    ProgressFilePathName_correct,OutputFirePerims_correct,
                    MetricFLP_correct,IgnitionProbabilitySeed_correct)

        result <- cbind(V1,V2)

        nameInp<-paste0("durval_",Duration_correct,"_cluster_",cluster_id,"_land_cover_",land_cover_id,"_durclass_",4,"_",WindDirection_correct,".input",sep="")
        write.table(result, nameInp,
                    sep=" ",row.names = FALSE,col.names=FALSE, quote=FALSE)


        if (j==1 & k==1){
          all.nameInp4 <- nameInp
        } else {
          all.nameInp4 <- rbind (all.nameInp4,nameInp)}

      }}
  }else{
    all.nameInp4 <- data.frame()
  }



  #dur 5

  dur_loop5 <- subset(FireListFile_correct_df_all_dur_all_all, duration_name == 5)





  if(!is.na(Duration.5_correct[1])){

    for(j in 1:length(Duration.5_correct)) {
      Duration_correct<- Duration.5_correct[j]


      for(k in 1:nrow(dur_loop5)){
        FireListFile_correct_final <- dur_loop5[k,"fullName"]
        Folder_right <- gsub("/", paste("\\\\"), Folder.fconstmtt)

        FireListFile_right <-gsub("/", paste("\\\\"), FireListFile)

        FireListFile_correct_final <- paste0(FireListFile_right,"\\",FireListFile_correct_final)

        WindDirection_correct <- dur_loop5[k,"direction"]
        cluster_id <- as.numeric(dur_loop5[k,"cluster_name"])
        land_cover_id <- dur_loop5[k,"land_cover_id"]
        land_cover_id <- gsub(".txt","",land_cover_id)
        landscape_correct_loop <- dur_loop5 [k,"LCPName"]
        WindSpeed_correct <- dur_loop5 [k,"WS"]
        FmsFile_correct <- dur_loop5 [k,"full_name_fms"]

        landscape_correct_loop <- gsub(".tif.input","",landscape_correct_loop)

        landscape_name <- as.character(landscape_correct_loop)

        OutputsName_correct <- paste0(OutputsFolder_correct,"\\durval_",Duration_correct,"_cluster_",cluster_id,"_durclass_",5,"_",WindDirection_correct,"_land_cover_",land_cover_id,sep="")

        Folder_right <- gsub("/", paste("\\\\"), Folder.fconstmtt)
        Folder_right_landscape <- gsub("/", paste("\\\\"), landscape)
        landscape_correct_loop_full_name <- paste0(Folder_right_landscape,"\\",landscape_correct_loop)
        FmsFolder_right <- gsub("/", paste("\\\\"), FmsFolder)

        FmsFile_correct_full_name <- paste0(FmsFolder_right,"\\",FmsFile_correct)

        V2 <- rbind(landscape_correct_loop_full_name,CrownFireMethod_correct,
                    customfmd_correct,FmsFile_correct_full_name,
                    Resolution_correct,GridDistanceUnits_correct,
                    WindSpeed_correct,WindDirection_correct,
                    Duration_correct,NumFires_correct,
                    FireListFile_correct_final,SpotProbability_correct,
                    ThreadsPerFire_correct,OutputsName_correct,
                    ProgressFilePathName_correct,OutputFirePerims_correct,
                    MetricFLP_correct,IgnitionProbabilitySeed_correct)

        result <- cbind(V1,V2)

        nameInp<-paste0("durval_",Duration_correct,"_cluster_",cluster_id,"_land_cover_",land_cover_id,"_durclass_",5,"_",WindDirection_correct,".input",sep="")
        write.table(result, nameInp,
                    sep=" ",row.names = FALSE,col.names=FALSE, quote=FALSE)


        if (j==1 & k==1){
          all.nameInp5 <- nameInp
        } else {
          all.nameInp5 <- rbind (all.nameInp5,nameInp)}

      }}
  }else{
    all.nameInp5 <- data.frame()
  }


  all.nameInp_final <- rbind(all.nameInp,all.nameInp2,all.nameInp3,all.nameInp4,all.nameInp5)
  Folder_right <- gsub("/", paste("\\\\"), Folder.fconstmtt)
  batfile <- cbind (paste0(Folder_right,"\\bin\\FConstMTT"),all.nameInp_final)


  write.table(batfile, "my_batch_1.bat",
              sep=" ",row.names = FALSE,col.names=FALSE, quote=FALSE)

  if(Run.fconstmtt==1){

    shell.exec(paste0(OutputsFolder_correct,"\\my_batch_1.bat"))
    return("Fconsmtt running! Take a break and come back soon")}

  return("Files generated!")
}

